### ISSUE TITLE
Ubertooth Wireshark Plugin - Wireshark 1.12.6

### ISSUE THREAD

**Issue by blong0159** [greatscottgadgets/ubertooth#104]
Trying to build the ubertooth wireshark plugin on Kali Linux 2.0 VM on Mac OSX...  Using the following:
- Kismet-2013-03-R1B
- libbtbb-2014-02-R4
- Ubertooth-2014-02-R2

When attempting to build the wireshark plugin, I get the following error in the image: 

<img width="1064" alt="screen shot 2015-08-23 at 19 52 55" src="https://cloud.githubusercontent.com/assets/13937080/9432036/b3364106-49d0-11e5-8fb5-532f6dc0b9f7.png">

The files do exist ... Do I need to statically link the locations of the files?

**Comment by dominicgs** [comment]
It's strange that it finds epan/proto.h but not epan/emem.h especially as the files are both in the same place.

I think you'll need to specify the path to the headers, above the epan directory.

**Comment by dominicgs** [comment]
Additionally: the 2014-04 release version of the plugin does not build against wireshark 1.12 as one of the features that we use was removed.

You may use the git version of the plugin without using the git version of libbtbb to fix the problem.

**Comment by blong0159** [comment]
Ran git clone https://github.com/greatscottgadgets/libbtbb.git

Navigated to libbtbb/wireshark/plugins/btbb

Ran the following: 

cmake .
make 
make install 

Get the following screen ...

<img width="1023" alt="screen shot 2015-08-24 at 07 44 29" src="https://cloud.githubusercontent.com/assets/13937080/9443096/1f518680-4a34-11e5-8602-4b711e6e42b2.png">

Then copy btbb.so to /usr/local/lib/kismet as this is what is configured in the kismet_ui.conf file for loading plugins ...  Then get the following ...  Failed to find kis_plugin_info in btbb.so

<img width="1096" alt="screen shot 2015-08-24 at 07 37 19" src="https://cloud.githubusercontent.com/assets/13937080/9443172/79ed9d68-4a34-11e5-8fdb-79da39c43f99.png">


Looks like I am still missing something ...

Thanks for any assistance

**Comment by dominicgs** [comment]
The btbb.so plugin is the Wireshark plugin, it has nothing to do with Kismet.

The Kismet plugin is in the Ubertooth host/kismet/plugin-ubertooth directory.

**Comment by blong0159** [comment]
Dominic ::

Thanks for the notes... Got myself caught up between Kismet and Wireshark.  Biggest thing is it appears Kismet was taking my settings from /usr/local/etc/kimset.conf versus /etc/kismet.conf....

Was able to get everything up and running as well as successfully did the updates to 2015-09-R2 ...  All set, thanks!

**Comment by dominicgs** [comment]
That's great to hear, thanks for letting me know.  I'll close this issue now.
