### ISSUE TITLE
Wiki update: filter in "Capturing BLE in Wireshark"

### ISSUE THREAD

**Issue by arvindraghavan** [greatscottgadgets/ubertooth#107]
The filter should be:

btle.data_header.length > 0 || btle.advertising_header.pdu_type == 0x05

**Comment by mikeryan** [comment]
Thanks for pointing out this inaccuracy, it's been fixed.

In the future we encourage you to make such edits directly, as the Wiki allows for that.

**Comment by arvindraghavan** [comment]
Thanks, and will make edits if needed in the future. I am still in the "looking around" mode, so I didn't want to put in something that was not fully verified.
