### ISSUE TITLE
include rx_only and rxtx firmware in release

### ISSUE THREAD

**Issue by ZeroChaos-** [greatscottgadgets/ubertooth#111]
Please modify the build system so the release tarballs can include an rx_only and an rxtx version of the firmware so that users only need to download one tarball which includes all the ubertooth code and both versions of the firmware.  While sometimes the ability to tx is great, other times the ability to prove you cannot tx is required for a specific engagement.  Having both at the ready in one package is an advantage for users.

**Comment by dominicgs** [comment]
Support for Rx only builds (by setting DISABLE_TX as an environment variable) added in 7870417

Added to release script in ba7ff6d
