### ISSUE TITLE
/libbtbb/lib/src/pcap.ng-bt.c:436:assemble_pcap_le_packet: Assertion 'caplen <= 48' failed. Aborted.

### ISSUE THREAD

**Issue by omarsohail** [greatscottgadgets/ubertooth#117]
Hey,
we're currently working on a bluetooth sniffing project using ubertooth and kali linux for the operating system. We seem to keep getting this error every time the ubertooth attempts to sniff packets from a android smartphone (Samsung I9500 Galaxy S4). The process starts but eventually after a few minutes shows this error and aborts. Any help would be great
thanks

**Comment by dominicgs** [comment]
This looks to be related to two pull requests for libbtbb (25 and 26).
