### ISSUE TITLE
Remote controller key's press can be captured and send pressed key bluetooth signal to the player using Ubertooth one, is it possible?

### ISSUE THREAD

**Issue by brijeshkum** [greatscottgadgets/ubertooth#144]
I want to capture bluetooth signal as remote controller keys and send pressed key to player using ubertooth one.

Is it possible with uberooth one? please suggest.

**Comment by mikeryan** [comment]
Depends, what kind of remote controller are you talking about? If it's BLE, there's some tiny chance that this can be accomplished.

**Comment by brijeshkum** [comment]
Hi Mike,


Remote controller is Bluetooth Smart device.


is there any way to capture signal or opcode generated by remote controller?


Thanks & Regards,

Brijesh Kumar

________________________________

**Comment by mikeryan** [comment]
You may be able to capture connections using ```ubertooth-btle -f -r capture.pcapng```, and by analyzing the contents you can see how keypresses are sent. You will likely have to connect and disconnect the remote repeatedly until Ubertooth captures the connection.
