### ISSUE TITLE
ubertooth-btle master branch write-to-file segfault

### ISSUE THREAD

**Issue by Crypt0s** [greatscottgadgets/ubertooth#147]
All file-write options in ubertooth-btle (in the master branch) fail with a segfault:

>  ubertooth-btle -p -r /tmp/file
> Segmentation fault (core dumped)

> ubertooth-btle -p -q /tmp/pie
> Segmentation fault (core dumped)

**Comment by elli89** [comment]
I see! This issue is caused by my latest patches. I will fix this.

**Comment by dominicgs** [comment]
Fixed in b28d9fc by @elli89
