### ISSUE TITLE
ubertooth-rx PCAPNG bug

### ISSUE THREAD

**Issue by Crypt0s** [greatscottgadgets/ubertooth#152]
Using latest libbtbb and ubertooth from git master.

attempting to write to a pcapng file with ubertooth-rx fails.  The PCAPNG file is successfully created, but no data will be written past the creation of the file header despite data being recovered and displayed on stdout by the ubertooth-rx tool.

**Comment by dominicgs** [comment]
@Crypt0s Pull request #154 claims to fix this bug.  If you are able to, could you test whether or not the tools in the git repository are working as you expect?
