### ISSUE TITLE
Capturing 2 BLE connections in Wireshark

### ISSUE THREAD

**Issue by schoensn** [greatscottgadgets/ubertooth#153]
Hi,
is it possible to use `ubertooth-btle` to capture two connections? 

i have a master who is connected to two peripherals over ble and I want to capture the data of both devices.

**Comment by mikeryan** [comment]
It's not possible with the current firmware. The hardware is capable, especially given the two connections are from a single master, but it would require significant firmware engineering that isn't planned any time soon. Apologies!
