### ISSUE TITLE
Hopping sequence calculated causes RAM leak in Kismet

### ISSUE THREAD

**Issue by dominicgs** [greatscottgadgets/ubertooth#158]
From Anh Tu Duong on the mailing list:

```
every time my ubertooth One displays "Calculating complete hopping sequence" and
 "Hopping sequence calculated" the RAM of the process kismet_server increases by
 around 150MB. Since my oDroid C1+ only has 1GB RAM I cannot operate that long.
 After 3 or 4 hopping sequence calculations my kismet_server crashes.
```

**Comment by elli89** [comment]
The hopping sequence stores one channel number for every possible value. Thus it is an array of 2^27 uint8_t values, which consumes about 128 MiB. So I would not consider this a bug but rather a consequence of calculating multiple hopping patterns.

A solution would be to run kismet only in survey mode without trying to follow piconets or to filter for only one piconet and its hopping sequence.
