### ISSUE TITLE
Little errors under  IAR ARM compiler, part 2

### ISSUE THREAD

**Issue by sevstels** [greatscottgadgets/ubertooth#164]
ubertooth-master from 7 March

IAR ARM very good compiler. 
Code "bluetooth_rxtx" can`t work properly with 24 errors.

Error[Pe018]: expected a ")" bluetooth_rxtx.c 1298 
cc2400_set(FREND,   0b1011);    // amplifier level (-7 dBm, picked from hat)
For compilers compatibility, here should be change 0b1011 to hex: 0x0B

Next...
Building configuration: ubertooth-one - Debug 
Updating build tree... 
ubertooth_usb.c  
Error[Pe120]: return value type ("void *") does not match the function type ("usb_pkt_rx *")  rx-tx\ubertooth_usb.c 241 
Error[Pe120]: return value type ("void *") does not match the function type ("usb_pkt_rx *")  rx-tx\ubertooth_usb.c 256 
Error[Pe140]: too many arguments in function call  rx-tx\ubertooth_usb.c 268 
Error while running C/C++ Compiler 
bluetooth.c  
bluetooth_rxtx.c  
Warning[Pe068]: integer conversion resulted in a change of sign  bluetooth_rxtx.c 63 
Warning[Pe068]: integer conversion resulted in a change of sign  bluetooth_rxtx.c 64 
Warning[Pe177]: variable "ac_copy" was declared but never referenced  bluetooth_rxtx.c 335 
Warning[Pe177]: variable "clock_offset" was declared but never referenced  bluetooth_rxtx.c 337 
Warning[Pe177]: label "rx_continue" was declared but never referenced  bluetooth_rxtx.c 1534 
Warning[Pe174]: expression has no effect  bluetooth_rxtx.c 1584 
Warning[Pe546]: transfer of control bypasses initialization of:  bluetooth_rxtx.c 1668 
            variable "ret" (declared at line 1709 of " bluetooth_rxtx.c") 
Warning[Pe546]: transfer of control bypasses initialization of:  bluetooth_rxtx.c 1693 
            variable "ret" (declared at line 1709 of " bluetooth_rxtx.c") 
Warning[Pe177]: variable "tmp" was declared but never referenced  bluetooth_rxtx.c 1598 
Warning[Pe546]: transfer of control bypasses initialization of:  bluetooth_rxtx.c 1788 
            variable "p" (declared at line 1798 of " bluetooth_rxtx.c") 
            variable "whit" (declared at line 1801 of " bluetooth_rxtx.c") 
            variable "len" (declared at line 1810 of " bluetooth_rxtx.c") 
            variable "total_transfers" (declared at line 1816 of " bluetooth_rxtx.c") 
Warning[Pe546]: transfer of control bypasses initialization of:  bluetooth_rxtx.c 1812 
            variable "total_transfers" (declared at line 1816 of " bluetooth_rxtx.c") 
Warning[Pe177]: variable "adv_addr" was declared but never referenced  bluetooth_rxtx.c 2007 
Warning[Pe177]: variable "crc" was declared but never referenced  bluetooth_rxtx.c 2011 
Error[Pe513]: a value of type "int (*)()" cannot be assigned to an entity of type "data_cb_t"  bluetooth_rxtx.c 2321 
Error[Pe167]: argument of type "uint8_t" is incompatible with parameter of type "ego_mode_t"  bluetooth_rxtx.c 2575 
Error while running C/C++ Compiler 
usbcontrol.c  
Error[Pe144]: a value of type "void *" cannot be used to initialize an entity of type "int (*)(TSetupPacket *, int *, U8 **)"  common\lpcusb\target\usbcontrol.c 69 
Error[Pe144]: a value of type "void *" cannot be used to initialize an entity of type "int (*)(TSetupPacket *, int *, U8 **)"  common\lpcusb\target\usbcontrol.c 69 
Error[Pe144]: a value of type "void *" cannot be used to initialize an entity of type "int (*)(TSetupPacket *, int *, U8 **)"  common\lpcusb\target\usbcontrol.c 69 
Error[Pe144]: a value of type "void *" cannot be used to initialize an entity of type "int (*)(TSetupPacket *, int *, U8 **)"  common\lpcusb\target\usbcontrol.c 69 
Error[Pe144]: a value of type "void *" cannot be used to initialize an entity of type "unsigned char *"  common\lpcusb\target\usbcontrol.c 71 
Error[Pe144]: a value of type "void *" cannot be used to initialize an entity of type "unsigned char *"  common\lpcusb\target\usbcontrol.c 71 
Error[Pe144]: a value of type "void *" cannot be used to initialize an entity of type "unsigned char *"  common\lpcusb\target\usbcontrol.c 71 
Error[Pe144]: a value of type "void *" cannot be used to initialize an entity of type "unsigned char *"  common\lpcusb\target\usbcontrol.c 71 
Error[Pe042]: operand types are incompatible ("int (*)(TSetupPacket *, int *, unsigned char **)" and "void *")  common\lpcusb\target\usbcontrol.c 108 
Error[Pe167]: argument of type "void *" is incompatible with parameter of type "unsigned char *"  common\lpcusb\target\usbcontrol.c 215 
Error while running C/C++ Compiler 
usbstdreq.c  
Error[Pe144]: a value of type "void *" cannot be used to initialize an entity of type "TFnHandleRequest *"  common\lpcusb\target\usbstdreq.c 76 
Error[Pe144]: a value of type "void *" cannot be used to initialize an entity of type "U8 const *"  common\lpcusb\target\usbstdreq.c 78 
Warning[Pe177]: variable "bInterfaceNumber" was declared but never referenced  common\lpcusb\target\usbstdreq.c 156 
Error[Pe042]: operand types are incompatible ("TFnHandleRequest *" and "void *")  common\lpcusb\target\usbstdreq.c 584 
Error while running C/C++ Compiler 
usbhw_lpc.c  
Error[Pe144]: a value of type "void *" cannot be used to initialize an entity of type "void (U8) *"  common\lpcusb\target\usbhw_lpc.c 75 
Error[Pe144]: a value of type "void *" cannot be used to initialize an entity of type "void (U16) *"  common\lpcusb\target\usbhw_lpc.c 79 
Error[Pe042]: operand types are incompatible ("void (U16) *" and "void *")  common\lpcusb\target\usbhw_lpc.c 546 
Error[Pe042]: operand types are incompatible ("void (U8) *" and "void *")  common\lpcusb\target\usbhw_lpc.c 566 
Error[Pe042]: operand types are incompatible ("void (*)(U8, U8)" and "void *")  common\lpcusb\target\usbhw_lpc.c 593 
Error[Pe513]: a value of type "void *" cannot be assigned to an entity of type "unsigned int volatile *"  common\lpcusb\target\usbhw_lpc.c 850 
Error while running C/C++ Compiler 
 
Total number of errors: 24 
Total number of warnings: 14

**Comment by dominicgs** [comment]
Given that we do not target the IAR compiler and you have since successfully compiled using Visual Studio, I am closing this issue.
