### ISSUE TITLE
Error with Ubertooth One #121a

### ISSUE THREAD

**Issue by garyv100** [greatscottgadgets/ubertooth#165]
Hi Dominic,

I have just purchased Ubertooth One w/ firmware release dated back to 2012.

I am running Ubuntu 14.04 LTS in VMWare Workstation 11.  It looks like that there were similar issues w/ VM that were resolved by adding filters to USB device which I do not know how to do in VMware. If someone could help me with that - it would be great.

This is what I get when I try to update the firmware for 2015.
///////////////////////////////////////////////////////////////////////////
garyv@ubuntu:~/ubertooth/ubertooth-2015-10-R1/ubertooth-one-firmware-bin$ sudo ubertooth-dfu -d bluetooth_rxtx.dfu -r
libUSB Error: Command Error:  (-1)
Switching to DFU mode...
Checking firmware signature
.......................................................................................................................................
libUSB Error: Command Error:  (-1)
/////////////////////////////////////////////////////////////////////////////
When I check rev:
garyv@ubuntu:/usr/local/bin$ ./ubertooth-util -v
Firmware revision: 2015-10-R1

First question, given the above, did the firmware updated correctly?

To see if it did, for starters i tried to replicate your youtube demo using:
////////////////////////////////////////////////////////
sudo ubertooth-scan -b hci0 -t 40 –x 
Ubertooth scan
systime=1457634961 ch=10 LAP=f19d9a err=2 clk100ns=2335214731 clk1=373634 s=-54 n=-62 snr=8
systime=1457634971 ch=57 LAP=a667b3 err=2 clk100ns=2429973401 clk1=388796 s=-52 n=-63 snr=11
??:??:??:F1:9D:9A
AFH map: 0x00040000000000000000
??:??:??:A6:67:B3
AFH map: 0x00000000000000020000
//////////////////////////////////////////////////////////////////
or sometimes I get noting, it just hangs
///////////////////////////////////////////////////////////////
garyv@ubuntu:~/ubertooth/ubertooth-2015-10-R1/ubertooth-one-firmware-bin$ sudo ubertooth-scan -b hci0 -t 40 –x

Ubertooth scan
///////////////////////////////////////////////////////////////////

Is this a VMWare issue, am I doing something wrong, how do I fix it?

Many thanks,

Gary

**Comment by dominicgs** [comment]
Yes, that shows a successful firmware update.  The libUSB errors are due to the device resetting itself while we are connected to it, which are hard to remove.  I'll try to suppress them in a future release.

Your second issue could be a VMWare issue or it could be that you aren't generating enough traffic for the Ubertooth to find the addresses.

Which version of the host code are you running?  ubertooth-rx -V should tell you.

**Comment by garyv100** [comment]
Dominic,

Thank you for responding to me.

I have set up a brand new machine with ubuntu 14.04 LTS directly on it (no
VM of any kind) w/ all the updates.

I have installed the latest the latest 2015 as per:
https://github.com/greatscottgadgets/ubertooth/wiki/Build-Guide

I have reloaded firmware and it did it perfectly:
//////////////////////////////////////
ubertooth-dfu -d bluetooth_rxtx.dfu -r
[sudo] password for garyv1:
Switching to DFU mode...
Checking firmware signature
.......................................................................................................................................
Detached
//////////////////////////////////////

However for the second issue I still have the same problem when I do:
//////////////////////////////////////////
garyv1@adtech:/usr/local/bin$ sudo ubertooth-scan -b hci0 -t 40

Ubertooth scan
systime=1457726544 ch=24 LAP=ff08ae err=1 clk100ns=299616267 clk1=47939
s=-69 n=-80 snr=11
systime=1457726554 ch=62 LAP=5afaa1 err=2 clk100ns=401074637 clk1=64172
s=-57 n=-72 snr=15
??:??:??:FF:08:AE
AFH map: 0x00000001000000000000
??:??:??:5A:FA:A1
AFH map: 0x00000000000000400000
//////////////////////////////////////////
or sometimes it hangs as before.

What i also noticed is the second red light next to the green one comes on
and stays on when the Ubertooth hangs.

This is what I get for the host version:
////////////////////////////////////
garyv1@adtech:/usr/local/bin$ ./ubertooth-rx -V
libubertooth 0.2 (GITDIR-NOTFOUND), libbtbb 0.3 (GITDIR-NOTFOUND)
////////////////////////////////////

Question, what do you mean by: "... or it could be that you aren't
generating enough traffic for the Ubertooth to find the addresses."?

Many thanks,

Gary

**Comment by dominicgs** [comment]
@garyv100 I think this may be a bug in the way that we handle the timeout in ubertooth-scan, i.e. it sometimes hangs and misses the end of the timeout.

**Comment by garyv100** [comment]
Dominic, i have seen this happen.  It looks like it happens more frequently under the conditions that force timeout - in low or no traffic or when the signal is week. Hope this helps.

On another subject.  In your Youtube demo "Bluetooth Packet Sniffing Using Project Ubertooth", correct me if i'm wrong, you mentioned that you were working on Spoofing, have you made any headway? 
Is it possible to spoof master?

Thank you.

**Comment by dominicgs** [comment]
When you say "conditions that force timeout" do you mean USB timeout?

I haven't gotten anywhere with packet injection, although it's possible to spoof a master device's address with a regular Bluetooth dongle, I haven't seen this yield better results yet.

**Comment by garyv100** [comment]
I do not know if it is USB timeout or not.  What I see is that sometimes it hangs in Ubertooth scan as per my original email:

or sometimes I get noting, it just hangs
///////////////////////////////////////////////////////////////
garyv@ubuntu:~/ubertooth/ubertooth-2015-10-R1/ubertooth-one-firmware-bin$ sudo ubertooth-scan -b hci0 -t 40 –x

Ubertooth scan
// this is where it hangs
///////////////////////////////////////////////////////////////////

What i mean by "conditions that force timeout" is low or no packet rate or low signal that Ubertooth is trying to sniff.  I assume that this is when the timer kicks in and ends the scan process.

It also happens with Ubuntu directly on the machine (no VM of any kind) and with the latest software and firmware update as of several days ago.

**Comment by dominicgs** [comment]
The way this code works is that we set a timer for x seconds and when that triggers we gracefully shut down the process.  Unfortunately it seems that there are conditions that cause this to fail.  I'm interested that it's more common when there are fewer/no packets.

**Comment by garyv100** [comment]
What I think it looks like is that under certain conditions during the timeout period something breaks    and the processor freezes before the timer expires. After all, correct me if i'm wrong, this timer should operate as a "Watchdog Timer" to end and if necessary restart the process regardless of whether or not the operation was successful.  

Question, are you running the timer on the same process or thread that sniffs the packets?

Also, I've seen freezing happen when two slaves try to pair w/ the same master.  Another indication that something breaks before the timer expires.  If the the scanner and the timer run on the same process or thread when scanner breaks before timer expires - we get ..........................
