### ISSUE TITLE
ubertooth-dfu segmentation fault

### ISSUE THREAD

**Issue by shadyproject** [greatscottgadgets/ubertooth#166]
I tried to update the firmware using the methods outlined on the [Firmware page](https://github.com/greatscottgadgets/ubertooth/wiki/Firmware), and the only result I get is 

could not open Ubertooth device 
[1]    24111 segmentation fault  ubertooth-dfu -d bluetooth_rxtx.dfu -r

I'm running OS X Yosemite 10.10.5

**Comment by shadyproject** [comment]
Realized now this is because it can't open the device.  Closing, sorry for the noise.

**Comment by dominicgs** [comment]
While a self-closed bug is my favourite kind. We should probably fix this
to give a sensible error message.
