### ISSUE TITLE
Issues with getting ubertooth one to work in kismet - ubuntu 14.04

### ISSUE THREAD

**Issue by OpenFerret** [greatscottgadgets/ubertooth#17]
Hi there,

I've followed the wiki for the installation of the ubertooth one tools and then compiled and installed kismet as per these instructions:

sudo apt-get install libpcap0.8-dev libcap-dev pkg-config build-essential libnl-dev libncurses-dev libpcre3-dev libpcap-dev libcap-dev
wget https://kismetwireless.net/code/kismet-2013-03-R1b.tar.xz
tar xf kismet-2013-03-R1b.tar.xz
cd kismet-2013-03-R1b
ln -s ../ubertooth-2014-02-R2/host/kismet/plugin-ubertooth .
./configure
make && make plugins
sudo make suidinstall
sudo make plugins-install
Add "pcapbtbb" to the "logtypes=..." line in kismet.conf

But kismet still doesn't recongnise the ubertooth as a source and there is no ubertooth plugin to select in the plugins list.

Has anyone managed to get this working in Ubuntu 14.04 LTS and can they share how please?

Many thanks!

**Comment by buidang** [comment]
Hi guys. Help me
"Couldn't load module /usr/local/lib/wireshark/plugins/1.12.8/packet-openflow.so: /usr/local/lib/wireshark/plugins/1.12.8/packet-openflow.so: undefined symbol: check_col"

**Comment by dominicgs** [comment]
@buidang That error has nothing to do with this issue or the Ubertooth project.  I suggest you ask the Wireshark developers or the developers of the OpenFlow dissector.
