### ISSUE TITLE
why i upgrade  hint:libUSB Error: Timeout:  (-7)

### ISSUE THREAD

**Issue by Robinchenjiaquan** [greatscottgadgets/ubertooth#174]
root@ubuntu:/home/robin/Downloads/ubertooth-2015-09-R2/ubertooth-one-firmware-bin# ubertooth-dfu -d bluetooth_rxtx.dfu -rlibUSB Error: Timeout:  (-7)
Switching to DFU mode...
Unable to find Ubertooth
root@ubuntu:/home/robin/Downloads/ubertooth-2015-09-R2/ubertooth-one-firmware-bin#

**Comment by linuxn00b** [comment]
Try the following command to dump more:
LIBUSB_DEBUG=8 ubertooth-dfu -d bluetooth_rxtx.dfu -r

You may find what's going on from the debug info.


On 03/29/2016 11:14 AM, Robinchenjiaquan wrote:
>
> root@ubuntu:/home/robin/Downloads/ubertooth-2015-09-R2/ubertooth-one-firmware-bin# 
> ubertooth-dfu -d bluetooth_rxtx.dfu -rlibUSB Error: Timeout: (-7)
> Switching to DFU mode...
> Unable to find Ubertooth
> root@ubuntu:/home/robin/Downloads/ubertooth-2015-09-R2/ubertooth-one-firmware-bin# 
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/greatscottgadgets/ubertooth/issues/174>
>


-- 
Best Regards,

Fudong

--------------------------------------------

Hisense RD
QingDao, China

Phone: +86 0532 5575 5430
www.hisense.com

**Comment by dominicgs** [comment]
@Robinchenjiaquan are you running in a virtual machine?  Ubertooth changes USB ID when it switches to DFU mode, if you're passing it through to the VM, then you'll need to pass through the DFU ID too.

**Comment by luxuguang-leo** [comment]
> @Robinchenjiaquan are you running in a virtual machine? Ubertooth changes USB ID when it switches to DFU mode, if you're passing it through to the VM, then you'll need to pass through the DFU ID too.

Could you tell me how to do that in details?I got this issue in VM, but seems every similar have no final soluction. Thanks
