### ISSUE TITLE
Wireshark complains pcapbtbb file is Malformed

### ISSUE THREAD

**Issue by chawandi08** [greatscottgadgets/ubertooth#179]
After searching, I got to know that LAP and UAP and CLKN are not calucated by the host, so without these data wireshark fails to decode. 

How to make sure, if my host is capable of calucating or not ?

**Comment by dominicgs** [comment]
There is no way to be sure and you will often have packets that cannot be decoded.

Which tool are you using to receive these packets?  ubertooth-rx?  Kismet?
