### ISSUE TITLE
Ubertooth-one Sending data

### ISSUE THREAD

**Issue by jacky035** [greatscottgadgets/ubertooth#180]
Hi
Can you help me? I need to know if ubertooth-one can send packets. If yes, how?

Thx

**Comment by dominicgs** [comment]
Yes, but it depends very much on what sort of data you would like to transmit.  The radio is capable of transmitting and there are transmit features in the firmware, but there isn't a host too to transmit arbitrary packets, although it would be relatively straight forward to write one.

We are not able to transmit data in a Bluetooth piconet yet, there is considerably more work required to achieve that.

This discussion is probably better suited to the mailing list: https://lists.sourceforge.net/lists/listinfo/ubertooth-general
