### ISSUE TITLE
Ubertooth-scan

### ISSUE THREAD

**Issue by raviwithu** [greatscottgadgets/ubertooth#184]
Hi,

I mostly used ubertooth-btle but now i want to capture NFC, will ubertooth-scan captures that? i assuming ubertooth-btle capture only BLE not NFC. Also is there a way to capture in pcap file in ubertooth-scan like ubertooth-btle has?

**Comment by mikeryan** [comment]
Ubertooth cannot capture NFC.

ubertooth-scan only works with BR devices: it unmasks undiscoverable devices and fetches their device name. It has no option to log to PCAP.

ubertooth-rx is similar in that it will discover undiscoverable devices. It does not do any further querying. It has flags for capturing to PCAP.

**Comment by raviwithu** [comment]
Thanks a lot for the info. Also am looking for transimission of packets, i know Ubertooth supports it. but dont know where to start. Am looking for sending Vcard to PCE regitered client
