### ISSUE TITLE
Facing problem while compiling the btle wireshark plugin

### ISSUE THREAD

**Issue by Nag5115** [greatscottgadgets/ubertooth#196]
Hi All,
I'm at starting stage in this ubertooth project. while I'm compiling btle wireshark plugin in libbtbb library getting below errors. This error is same while compiling btbb wireshark plugin also.

/libbtbb-2015-10-R1/wireshark/plugins/btle/packet-btle.c: In function ‘dissect_btle’:
/libbtbb-2015-10-R1/wireshark/plugins/btle/packet-btle.c:408:11: error: ‘packet_info’ has no member named ‘private_data’
make[2]: *** [CMakeFiles/btle.dir/packet-btle.c.o] Error 1
make[1]: *** [CMakeFiles/btle.dir/all] Error 2
make: *** [all] Error 2

so,please provide solution to this problem.

Thanks...

**Comment by dominicgs** [comment]
Which version of Wireshark?

**Comment by Nag5115** [comment]
Thanks for replay...
I'm using wireshark stable version of 2.0.3 and I'm using all latest versions of libbtbb and ubertooth. while compiling the btle and btbb wireshark plugins it is showing this error "packet-btle.c:408:11: error: ‘packet_info’ has no member named ‘private_data" .

So, please provide solution to this problem...

Thanks...

**Comment by EMCP** [comment]
@Nag5115 see https://github.com/greatscottgadgets/ubertooth/issues/195

**Comment by dominicgs** [comment]
You do not need to build the BTLE plugins against any version of Wireshark after 1.12 as they are included in the Wireshark code.
