### ISSUE TITLE
uh oh, full_usb_buf not emptied

### ISSUE THREAD

**Issue by asad-lesani** [greatscottgadgets/ubertooth#205]
Hi,

I have two Ubertooth module connected to raspberry PI. Sometime I get `uh oh, full_usb_buf not emptied` error. How can I solve it? I already have upgraded the firmware to 2015, and I got latest version of libbtbb and ubertooth from Github.

Thanks.

**Comment by dominicgs** [comment]
This is caused by the host not keeping up with the rate at which the Ubertooth is sending data.  This could be due to host performance or USB performance.  With the raspberry pi I suspect it is a little of both.

We should handle this better though.  It is being tracked as #127
