### ISSUE TITLE
Unable to sniff from hm10

### ISSUE THREAD

**Issue by arunmagesh** [greatscottgadgets/ubertooth#217]
Hello.
I have Ubertooth One. Recently it stopped working in -f mode. It works like randomly. but it works on -p mode. But i am unable to see the packet address.

I connected HM10 to an arduino which sends a string to my mobile. No encryption. Just plain text. 
In wireshark. I am getting dump value in the data.

How can i sniff the data sending from my arduino?

[dump-pcapng.txt](https://github.com/greatscottgadgets/ubertooth/files/349548/dump-pcapng.txt)

**Comment by mikeryan** [comment]
If you are still having this problem, please reopen the issue.
