### ISSUE TITLE
libUSB Error: Command Error: (-9)

### ISSUE THREAD

**Issue by thwillingham** [greatscottgadgets/ubertooth#236]
### Steps to reproduce
1. download the latest ubertooth release
2. update the firmware
3. run ubertooth-rx

### Expected behaviour
The ubertooth-rx program should work

### Actual behaviour
I get an error:
libUSB Error: Command Error:  (-9)
Ubertooth running very old firmware found.
Please upgrade to latest released firmware.

### Version information
**Operating system**: Kali

**Ubertooth tools version (ubertooth-rx -V): libubertooth 0.3 (adeb80f), libbtbb 0.4 (8d6c49c)

**Ubertooth firmware version (ubertooth-util -v): Firmware revision: 2015-10-R1

**Comment by thwillingham** [comment]
A reinstallation of the software seemed to fix the issue.

**Comment by dominicgs** [comment]
It looks like you previously had the git version of the Ubertooth tools installed, which introduces the `Ubertooth running very old firmware found.` error message.

Running the 2015 release and the matching firmware has solved the problem.
