### ISSUE TITLE
Scanning Range

### ISSUE THREAD

**Issue by fgranado** [greatscottgadgets/ubertooth#237]
Hey, 
I have a quick question, Is there any way to adjust the scanning range (decrease)? I'm not sure if this is a possible configuration setting. I looked through some of the code and couldn't see exactly where I could modify it, and I've searched through previous issues but nothing came up for scanning ranges. I have rather small antenna already, I just want to get the range down to the size of a room? So maybe a range of approximately 10-15 feet? Thanks.

**Comment by mikeryan** [comment]
The CC2400 does not have any inbuilt capabilities to reduce the sensitivity of the receiver. You might try filtering based on RSSI, which is included with each received packet in the latest released firmware.
