### ISSUE TITLE
ubertooth_ui.so kismet server error

### ISSUE THREAD

**Issue by gracelee** [greatscottgadgets/ubertooth#250]
Hi guys, I am working on installing kismet with ubertooth, but everytime I run "sudo kismet or sudo kismet_server", I keep getting this error.
I followed "Building from git", so libbtb,ubertooth and kismet are all the latest versions.
My laptop runs ubuntu 16.04.
Can anybody please help me?

FATAL: Failed to open plugin '/usr/local/lib/kismet/ubertooth_ui.so': /usr/
       local/lib/kismet/ubertooth_ui.so: undefined symbol: _ZTI9Kis_Panel
FATAL: Failure during activating plugins

**Comment by dominicgs** [comment]
This looks like you have some kismet plugins installed from a previous
build. Do you have a kismet package installed from your distribution?
