### ISSUE TITLE
No firmware folder in 2017-03-r2

### ISSUE THREAD

**Issue by rdunne** [greatscottgadgets/ubertooth#258]
Hi 

Your release version for 2017-03-r2 is missing the ubertooth-one-firmware-bin fodler, 

coudl you update the folders . Thanks

**Comment by dominicgs** [comment]
The file `ubertooth-2017-03-R2.tar.xz` includes the binary firmware images in the ubertooth-one-firmware-bin directory.  The two download links labeled 'source code' are auto-generated by GitHub when we tag the repositiry, they don't contain the binary firmware.
