### ISSUE TITLE
Ubertooth & kismet build errors?

### ISSUE THREAD

**Issue by dreyes15** [greatscottgadgets/ubertooth#262]
I am trying to install the kismet plugin as specified in the third party instructions 
specifically I have run the following:
 however after following the steps described in the documentation when I run kismet I get the following 
<img width="1440" alt="screen shot 2017-05-01 at 10 40 32 am" src="https://cloud.githubusercontent.com/assets/5712088/25586595/3b074e78-2e5d-11e7-877f-1c3e4b153926.png">

### Version information
Ubuntu 16.04
Ubertooth 2017-03-R2
Kismet-2013-03-R1

**Comment by dominicgs** [comment]
Most of those look like permissions errors.  Is this running as root?  Or another user?

Has the ubertooth plugin installed anywhere?  What was the output of the `make install` command for the plugin?

**Comment by dreyes15** [comment]
That is the output running as both root and as a regular user, after running: `sudo make plugins-install` I receive the following output 
<img width="1440" alt="screen shot 2017-05-02 at 6 28 13 pm" src="https://cloud.githubusercontent.com/assets/5712088/25644733/84b28e12-2f65-11e7-8de9-500df011f4d2.png">

Could these errors have originated from the soft link? when I run `ln -s ../ubertooth-2017-03-R2/host/kismet/plugin-ubertooth .`
I get the error that says it failed to create the symbolic link '/plugin-ubertooth': file exists

**Comment by dreyes15** [comment]
I have kismet seeing the ubertooth one as a plugin now, I had to change the path of where the source code to kismet was it
<img width="1440" alt="screen shot 2017-05-02 at 6 28 13 pm" src="https://cloud.githubusercontent.com/assets/5712088/25645093/557067e8-2f68-11e7-95cb-b006cab39f7e.png">

This is what I get when clicking on the plugin, which I think is the correct output?

**Comment by dominicgs** [comment]
That looks better.  Try starting some Bluetooth devices nearby to see if you get any output?

**Comment by dreyes15** [comment]
There we go I am getting some packets now, thanks!
<img width="1440" alt="screen shot 2017-05-02 at 8 08 10 pm" src="https://cloud.githubusercontent.com/assets/5712088/25646190/25ca43f0-2f73-11e7-8cfd-ee2200e0b56e.png">

**Comment by dreyes15** [comment]
Hmm there seems to be another issue It seems after exiting the program the terminal says I have some packets, but upon opening the pcap file it says no packets collected, perhaps now it's a kismet issue?

**Comment by dreyes15** [comment]
<img width="1440" alt="screen shot 2017-05-02 at 8 20 42 pm" src="https://cloud.githubusercontent.com/assets/5712088/25646362/de9b0ea4-2f74-11e7-8132-16ac798b9389.png">
Here is a photo of what I output

**Comment by dominicgs** [comment]
Bluetooth has a packet scrambler (known as data whitening in the BT spec) that we can't decode when we first receive packets, we need more information about them.  Even when we can decode it, we can't always be sure of the size/modulation of the data section of the packet, so that can often be invalid or left out of the pcap.

It looks like in this case we were never able to unwhiten packet data.

**Comment by dreyes15** [comment]
Ok, so in this case it isn't necessarily a Kismet or Ubertooth problem. It is mostly an unwhiten packet data. Alright sounds good then if that's the case then this issue is resolved
Thanks!

**Comment by dominicgs** [comment]
I believe it should only produce one output file for Ubertooth captures.

**Comment by dreyes15** [comment]
Hmm ok well apart from the packets never being unwhiten it seems like all the issues I was having is fixed.

**Comment by Bella721** [comment]
When we use kismet to capture package, why it can't create pacpbtbb files?

**Comment by mikeryan** [comment]
Legacy Kismet is no longer supported by this project.
