### ISSUE TITLE
Add option to send binary to stdout

### ISSUE THREAD

**Issue by dadatuputi** [greatscottgadgets/ubertooth#263]
It doesn't appear possible to send binary data over stdout. In order to avoid using a named pipe for live Wireshark capture, it should be possible to simply pipe the output from ubertooth-btle to wireshark ala:

`# ubertooth-btle -"binary output parameter here" | wireshark -k -i -`

Thanks for your consideration. If this is already possible, please let me know as well.

**Comment by mikeryan** [comment]
I believe this will already work. Try it with `ubertooth-btle -c -`.
