### ISSUE TITLE
Bluetooth V5 support

### ISSUE THREAD

**Issue by tomsaul** [greatscottgadgets/ubertooth#265]
Has compatibility with the new standard been examined?  If the hardware is compatible, is there a plan to support this in the software/firmware?

**Comment by dominicgs** [comment]
There are a few different parts to the 5.0 spec, the Ubertooth hardware is compatible with some of them but not all.

The main sticking point would be 2MHz channels, which the CC2400 does not support.

**Comment by mikeryan** [comment]
The primary updates in BT 5.0:

- LE link layer packets > 37 bytes -- implemented as of 2018-06-R1
- LE coded PHY -- not implementable on existing hardware
- LE 2 Mbit/s data rate -- not implementable on existing hardware
