### ISSUE TITLE
Wrong LAP value displayed by Kismet

### ISSUE THREAD

**Issue by w31ha0** [greatscottgadgets/ubertooth#267]
### Steps to reproduce
1. Run kismet
2. Turn on bluetooth on  multiple phones

### Expected behaviour
Kismet should show different LAP values for each unique device

### Actual behaviour
Kismet only shows one LAP value of 9e:8b:33 to represent all devices

### Version information
**Operating system**: Kali Linux 2.0

**Ubertooth firmware version (ubertooth-util -v): Firmware version: 2017-03-R2 (API:1.02)

Kismet 2016-07-R1

**Comment by dominicgs** [comment]
9e:8b:33 is the inquiry LAP, it's used for discovering other devices when you scan.

In regular operation mode the only LAP shown will be for the master device.
