### ISSUE TITLE
Ubertooth-btle not hopping in promiscuos mode?

### ISSUE THREAD

**Issue by w31ha0** [greatscottgadgets/ubertooth#272]
### Steps to reproduce
1. Run ubertooth-btle -p with an active btle connection nearby.

### Expected behaviour
After a while, ubertooth-btle should hop along with the active btle connection.

### Actual behaviour
ubertooth-btle only displays "LE Promisc - Access Address:  xxxxxx" ,the access address it has found and gets stuck there, even after a long time

**Comment by mikeryan** [comment]
It's possible / likely that Ubertooth did not recover the correct access address. It is also possible that the connection is not using all 37 data channels, in which case promiscuous mode will not work.

Promiscuous mode is very unreliable. We recommend using follow mode if you can.

If you must ocntinue using promiscuous mode, then keep trying and possibly the other parameters will be recovered.
