### ISSUE TITLE
Can not update firmware

### ISSUE THREAD

**Issue by nyaz-asti** [greatscottgadgets/ubertooth#292]
### Steps to reproduce
1. Ubertooth firmware 534 API:1.00
2. Updating firmware gives me this message non-stop 'control message unsupported'
3. I'm hoping I just need a in between firmware to get the device updated? Like there's 2 or 3 firmware I need to update to, before I can load the latest? Thank you in advance.

**Comment by dominicgs** [comment]
If you connect pins 1 & 3 on the [expansion header](https://github.com/greatscottgadgets/ubertooth/wiki/Ubertooth-One#pins-and-leds) as you plug it in, you'll see a little light display from the LEDs.

If you run `ubertooth-dfu` while that's going on, it should work regardless of firmware version.

**Comment by nyaz-asti** [comment]
While I did get a different bootup connecting the pins, I'm getting the same message when I try to update the firmware.

**Comment by nyaz-asti** [comment]
Nevermind, I got it to work, thanks for your help. The lights dancing didn't last long, so I was quick and got it working when they were briefly. Thanks again.

**Comment by dominicgs** [comment]
I'm glad you got it working.  The timeout on the bootloader is rather short for historic reasons.  I'm sorry that it's a bit misleading.
