### ISSUE TITLE
option useless

### ISSUE THREAD

**Issue by XingweiLin** [greatscottgadgets/ubertooth#293]
### Steps to reproduce
1. `ubertooth-btle -A 38` or `ubertooth-btle -txx:xx:xx:xx:xx:xx`

### Expected behaviour
In `-A`, I want to change the default channel to 38,
In `-t`, I want to only listen to the specific BR_ADDR device

### Actual behaviour
all these options are useless.

### Version information
**Operating system**:
Linux kali 4.12.0-kali1-amd64 #1 SMP Debian 4.12.6-1kali6 (2017-08-30) x86_64 GNU/Linux
In vmware
**Ubertooth tools version (ubertooth-rx -V):**
libubertooth 1.0 (2017-03-R2), 
**libbtbb version:**
libbtbb 1.0 (2017-03-R2)
**Ubertooth firmware version (ubertooth-util -v):**
2017-03-R2

**Comment by mikeryan** [comment]
Both options definitely work on the latest firmware. -t will not limit the advertising packets you see, but it will prevent Ubertooth from following connections from any device other than the one you specify.

**Comment by XingweiLin** [comment]
But as for the `-A`, when I change use `-A 38`, ubertooth-one still listened on the channel 37.
```
ubertooth-btle -A 38 -f -c test.pcap &> out.txt
```
And as you can see, the results were still in channel 37.

![image](https://user-images.githubusercontent.com/15721702/31157467-c1e2223c-a8ed-11e7-8298-e3a1f6ed37c5.png)

**Comment by mikeryan** [comment]
Are you running the latest host and firmware? Paste the output of ubertooth-util -v

Try resetting the Ubertooth with ubertooth-util -r and see if you still have the same problem.

**Comment by XingweiLin** [comment]
```
root@kali:~# ubertooth-util -v
Firmware version: 2017-03-R2 (API:1.02)
```

Ubertooth-one is not stable in my environment.
When I try `ubertooth-util -r`, it failed:
![image](https://user-images.githubusercontent.com/15721702/31157898-be3a9ed6-a8f0-11e7-8b02-a9a189ad7095.png)

**Comment by dominicgs** [comment]
`libUSB Error: Operation timed out: (-7)` is a fairly common response to resetting the device, because the device resets and disconnects before the response has reached the host system.  This is especially common in virtual machines.
