### ISSUE TITLE
libUSB Error: Timeout: (-7)

### ISSUE THREAD

**Issue by ykram** [greatscottgadgets/ubertooth#296]
### Steps to reproduce
1. ubertooth-util -v

### Expected behaviour
Expect to see firmware on device

### Actual behaviour
Receive an error message:

libUSB Error: Timeout:  (-7)
Firmware revision: error: -7

### Version information
Kali 4.13.0-amd64

**Ubertooth tools version (ubertooth-rx -V):**
libubertooth 0.2

**libbtbb version:**
libbtbb 0.3

**Ubertooth firmware version (ubertooth-util -v):**
N/A

If you are reporting a problem that involves third party software 
(Wireshark/Kismet/etc), please report the version here.

### Output

Using `lsusb` after initially inserting the device shows:

`iManufacturer        1 Great Scott Gadgets`
`iProduct                 2 Ubertooth One`
`iSerial                     3 <omitted>`
...
`Device Status:         0x0000`
`  (Bus Powered)`

However, after I try to initiate a `ubertooth-util -v`, I receive an error saying that libUSB timed out (-7).

`lsusb -vd 1d50:6002` then shows that

`iManufacturer`, `iProduct` and `iSerial` are all showing as (Error) but the `Device Status` is still 0x0000.

**Comment by mikeryan** [comment]
Are you running Kali inside a VM? How many LEDs are lit, and what color are they?

**Comment by ykram** [comment]
This Kali being run via USB, not in a VM. I have 3 LEDs lit, 2 green and 1 red.

**Comment by dominicgs** [comment]
Do any of the other functions work?  e.g. `ubertooth_util -l`?  It should report the status of the LEDs.

**Comment by ykram** [comment]
Unfortunately, they do not. I get:

libUSB Error: Timeout:  (-7)
USR LED Status: -7

**Comment by dominicgs** [comment]
How about any of the other tools? e.g.'ubertooth-rx`?

Are you able to run `ubertooth-dfu` to update the firmware to the latest version?

**Comment by ykram** [comment]
`ubertooth-rx` and the other tools also return libUSB error -7.

`ubertooth-dfu -d bluetooth_rxtx.dfu -r` gives me the following:

libUSB Error: Operation timed out:  (-7)
Switching to DFU mode...
Unable to find Ubertooth

**Comment by ykram** [comment]
I tried installing the tools on a separate linux laptop running Ubuntu 16.04.3 and while I still get the -7 error from libUSB, `ubertool-util -v` gives me somewhat more information:

`libUSB Error: Operation timed out:  (-7)`
`Firmware version: error: -7 (API:1.02)`

**Comment by dominicgs** [comment]
I think we'll need to force your Ubertooth in to bootloader mode.  If you have a paper clip you can connect two pins on the expansion header: https://pbs.twimg.com/profile_banners/19587312/1354079866/1500x500

You'll need to run the `ubertooth-dfu -d bluetooth_rxtx.dfu -r` command while the lights are still flashing.

**Comment by ykram** [comment]
That looks like it did the trick! ubertooth-util shows the proper version
and capturing in WireShark world as expected. Thank you!
