### ISSUE TITLE
Packet Loss (USB or Baseband)

### ISSUE THREAD

**Issue by gomis8** [greatscottgadgets/ubertooth#303]
### Steps to reproduce
1. Start ubertooth-btle and use /tmp/fifo
2. Use wireshark to decode packets
3. Start sniffing

### Expected behaviour
All of the sniffed connection's packets should be displayed in wireshark, and transferred sucessfully betweeen the ubertooth and my PC

### Actual behaviour
Some packets, i.e. ATT and L2CAP fragments are ommited. I am sure that the are on-air and sucessfully transferred between the devices used. Conn interval is 15ms and I am sending notifications with and MTU of 185. The end device is notified by not every packet is found on the pcap file. 

Does this have anything to do with bulk mode usb transfers?

From what I researched, some changes have been previously made to have a FIFO. 
But bulk mode usb functions are commented in firmware/bluetooth_rxtx/ubertooth_usb.c
Any Ideas of what is happening? Can it be just baseband packet loss?(Everything is within 20cm)

### Version information
**Operating system**:Linux laptop 4.9.87-1-MANJARO #1 SMP PREEMPT Tue Mar 13 05:29:55 UTC 2018 x86_64 GNU/Linux

**Ubertooth tools version (ubertooth-rx -V):**
libubertooth 1.0 (2017-03-R2), libbtbb 1.0 (2017-03-R2)

**libbtbb version:**2017.03.R2-1

**Ubertooth firmware version (ubertooth-util -v):**
Firmware version: 2017-03-R2 (API:1.02)

If you are reporting a problem that involves third party software 
(Wireshark/Kismet/etc), please report the version here.
Wireshark 2.5.0

**Comment by mikeryan** [comment]
It is expected that some packets will be dropped. Please try the latest pre-release 2018-06-R1 as its packet capture rate is higher than previous versions.
