### ISSUE TITLE
Kismet can't create pcapbtbb file

### ISSUE THREAD

**Issue by Bella721** [greatscottgadgets/ubertooth#304]
### Steps to reproduce
1.When I run sudo kismet_server -c ubertooth this command in Ubuntu 14.04

### Expected behaviour
The result is shown below:
ERROR: Kismet was started as root, NOT launching external control binary.  
       This is NOT the preferred method of starting Kismet as Kismet will 
       continue to run as root the entire time.  Please read the README 
       file section about Installation & Security and be sure this is what 
       you want to do.
INFO: Reading from config file /usr/local/etc/kismet.conf
INFO: No 'dronelisten' config line and no command line drone-listen 
      argument given, Kismet drone server will not be enabled.
INFO: Created alert tracker...
INFO: Creating device tracker...
INFO: Registered 80211 PHY as id 0
ERROR: Failed to open user plugin directory (/root/.kismet//plugins/): No 
       such file or directory
INFO: Loaded info for plugin 'alertsyslog.so': Plugin name: 'ALERTSYSLOG' 
      Plugin version: '2013-03-R0' Plugin description: 'ALERTSYSLOG Plugin'
INFO: Activated plugin '/usr/local/lib/kismet/alertsyslog.so': 
      'ALERTSYSLOG' '2013-03-R0' 
INFO: Loaded info for plugin 'spectool_net.so': Plugin name: 'SPECTOOL' 
      Plugin version: '2013-03-R0' Plugin description: 'Spectool-Net'
INFO: Loaded info for plugin 'ubertooth.so': Plugin name: 'UBERTOOTH' 
      Plugin version: '2013-03-R0' Plugin description: 'Ubertooth plugin 
      for Bluetooth baseband protocol'
INFO: Pcap logging for type pcapbtbb
INFO: Activated plugin '/usr/local/lib/kismet/ubertooth.so': 'UBERTOOTH' 
      '2013-03-R0' 
INFO: Loaded info for plugin 'kismet-syslog.so': Plugin name: 'SYSLOG' 
      Plugin version: '2013-03-R0' Plugin description: 'SYSLOG Plugin'
ERROR: Kismet-Syslog not redirecting any messages to syslog because no 
       syslogtype= directive found in kismet.conf
INFO: Kismet-Syslog redirecting no messages to syslog
INFO: Activated plugin '/usr/local/lib/kismet/kismet-syslog.so': 'SYSLOG' 
      '2013-03-R0' 
INFO: Loaded info for plugin 'btscan.so': Plugin name: 'BTSCAN' Plugin 
      version: '2013-03-R0' Plugin description: 'Active Bluetooth scanning 
      plugin'
INFO: Activated plugin '/usr/local/lib/kismet/btscan.so': 'BTSCAN' 
      '2013-03-R0' 
INFO: Kismet will spend extra time on channels 1,6,11
INFO: Kismet will attempt to hop channels at 3 channels per second unless 
      overridden by source-specific options
INFO: Matched source type 'ubertooth' for auto-type source 'ubertooth'
INFO: Using default channel list 'UBERTOOTH' on source 'ubertooth'
INFO: Ubertooth using first USB device that looks like a Ubertooth
INFO: Created source ubertooth with UUID 
      57395750-3c1f-11e8-bba6-b8072e49dc03
INFO: Disabling channel hopping on source 'ubertooth' because it is not 
      capable of setting the channel.
INFO: Will attempt to reopen on source 'ubertooth' if there are errors
ERROR: TCP server bind() failed: Address already in use
FATAL: Failed to enable TCP listener for the Kismet UI server

### Actual behaviour
And kismet can't create pacpbtbb file.

### Version information
**Operating system**:

user@ubuntu:~$ ubertooth-rx -V
libubertooth 1.0 (2017-03-R2), libbtbb 1.0 (2017-03-R2)

user@ubuntu:~$ ubertooth-util -v
usb_claim_interface error -6
ubertooth-util - command line utility for Ubertooth Zero and Ubertooth One

user@ubuntu:~$ ubertooth-util -v
usb_claim_interface error -6
ubertooth-util - command line utility for Ubertooth Zero and Ubertooth One

If you are reporting a problem that involves third party software 
(Wireshark/Kismet/etc), please report the version here.

### Output
```
Insert any commandline or build output here
```

**Comment by mikeryan** [comment]
Legacy Kismet is no longer supported by this project.
