### ISSUE TITLE
Can't create connection: Input/output error in ubertooth-follow ?

### ISSUE THREAD

**Issue by Kumarasamy** [greatscottgadgets/ubertooth#305]
### Steps to reproduce
1.  Connect the BTLE device which has MAC 00:00:50:13:2B:2F
2. Enter the ubertooth-follow -l132B2F -u50

### Expected behaviour
Tell us what you expect should happen
Connect and follow the traffic 
### Actual behaviour
Tell us what happens instead
throwing error after few secs

### Version information
**Operating system**:
4.14.0-kali3-686-pae

**Ubertooth tools version (ubertooth-rx -V):**
libubertooth 1.0 (2017-03-R2), 

**libbtbb version:**
libbtbb 1.0 (2017-03-R2)

**Ubertooth firmware version (ubertooth-util -v):**
Firmware version: 2017-03-R2 (API:1.02)
If you are reporting a problem that involves third party software 
(Wireshark/Kismet/etc), please report the version here.

### Output
```
Insert any commandline or build output here
```
Output:
ubertooth-follow -l132B2F -u50
Address given, assuming address is remote
Address: 00:00:50:13:2B:2F
Can't create connection: Input/output error

**Comment by dominicgs** [comment]
Ubertooth follow is a tool designed to use a standard Bluetooth adapter to follow Bluetooth Basic Rate connections (it's very experimental).

If you're looking at BTLE communications, then I recommend that you look at `ubertooth-btle`
