### ISSUE TITLE
Ubertooth (on Ubuntu) does not follow the BLE device with given address

### ISSUE THREAD

**Issue by Phase-angle-regulating-transformer** [greatscottgadgets/ubertooth#309]
Hi there

I want to sniff some data packages between two Bluetooth Low Energy Devices with Ubertooth One.

I followed steps from build guide https://github.com/greatscottgadgets/ubertooth/wiki/Build-Guide. Next I tried to sniff my devices using "ubertooth-btle -f -a(address) -c /tmp/pipe" but it does not work. The results of this operation are the same like "ubertooth-btle -f -c /tmp/pipe". Other variants of this command with -t or -s does not work too. It does not hopping between channels, only shows some addresses and infos on chosen channel.

**Comment by dominicgs** [comment]
I didn't write the `ubertooth-btle` tool, so this may not be correct, but I believe you need to run it as two separate commands:
```
ubertooth-btle -t <address>
ubertooth-btle -f -c /tmp/pipe
```

**Comment by mikeryan** [comment]
In the latest released firmware, you will receive advertising packets from all devices but only follow connections from the target device specified with -t.

In the le_phy branch's firmware, in addition to only following connections from the specified target device you will also only receive advertising packets to/from that device.

**Comment by Phase-angle-regulating-transformer** [comment]
Thanks mikeryan. So what are the steps to follow connection from one target device? I attempt to do this too, but it failed.  Maybe I did something wrong. I used function with -t but it is still not following this device.

**Comment by mikeryan** [comment]
It will likely take many tries to capture the connection. Just keep running ubertooth -f after you use -t and repeatedly disconnect and reconnect the devices. Ubertooth will eventually capture a connection. It can take 10+ tries sometimes.
