### ISSUE TITLE
libUSB: Pipe error (-9) when using le_phy firmware

### ISSUE THREAD

**Issue by gsingh93** [greatscottgadgets/ubertooth#313]
### Steps to reproduce
1. Build and flash the firmware from the le_phy branch
2. Run `ubertooth-btle -f -c /tmp/pipe`
3. Run Wireshark and capture from the pipe
4. Eventually `ubertooth-btle` will exit with the error:
```
libUSB Error: Pipe error:  (-9)
USB error
```

This usually happens in under a minute.

### Expected behaviour
`ubertooth-btle` should not exit. This is the behavior I see when using the 2017-03-R2 release.

### Actual behaviour
`ubertooth-btle` exits.

### Version information
**Operating system**: Ubuntu 16.04

**Ubertooth tools version (ubertooth-rx -V):**
```
gulshan@gulshan-thinkpad:~/code/opensource/ubertooth-le_phy/host/build$ ubertooth-util -V
ubertooth git- (gulshan@gulshan-thinkpad) Sat Jun  2 16:46:38 PDT 2018
gulshan@gulshan-thinkpad:~/code/opensource/ubertooth-le_phy/host/build$ ubertooth-rx -V
libubertooth 1.0 (2017-03-R2), libbtbb 1.0 (2017-03-R2)
```

**libbtbb version:**
2017-03-R2

**Ubertooth firmware version (ubertooth-util -v):**

```
$ ubertooth-util -v
Firmware version: git- (API:1.02)
```

If you are reporting a problem that involves third party software 
(Wireshark/Kismet/etc), please report the version here.

Wireshark version 2.2.6

**Comment by mikeryan** [comment]
Please try the latest fix in git master (one commit ahead of 2018-06-R1).

**Comment by gsingh93** [comment]
So far, this seems to be fixed. Thanks!

**Comment by ChenYenTing** [comment]
I meet the same problem.
Do you solve it.
