### ISSUE TITLE
Error during Wireshark Plugin Builds

### ISSUE THREAD

**Issue by Jeffrey-S** [greatscottgadgets/ubertooth#317]
Following build procedures for wireshark plugins, Ubuntu 18.04.  I get these series of errors during make. Any suggestions to resolve? 

[ 20%] Generating plugin.c
Scanning dependencies of target btbb
[ 40%] Building C object CMakeFiles/btbb.dir/plugin.c.o
[ 60%] Building C object CMakeFiles/btbb.dir/packet-btbb.c.o
/home/jeffrey/Desktop/Ubertooth/libbtbb-2017-03-R2/wireshark/plugins/btbb/packet-btbb.c: In function ‘dissect_dm1’:
/home/jeffrey/Desktop/Ubertooth/libbtbb-2017-03-R2/wireshark/plugins/btbb/packet-btbb.c:252:13: warning: implicit declaration of function ‘tvb_new_subset’; did you mean ‘tvb_raw_offset’? [-Wimplicit-function-declaration]
   pld_tvb = tvb_new_subset(tvb, offset, len, len);
             ^~~~~~~~~~~~~~
             tvb_raw_offset
/home/jeffrey/Desktop/Ubertooth/libbtbb-2017-03-R2/wireshark/plugins/btbb/packet-btbb.c:252:11: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   pld_tvb = tvb_new_subset(tvb, offset, len, len);
           ^
/home/jeffrey/Desktop/Ubertooth/libbtbb-2017-03-R2/wireshark/plugins/btbb/packet-btbb.c:259:12: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
    pld_tvb = tvb_new_subset(tvb, offset, len, len);
            ^
/home/jeffrey/Desktop/Ubertooth/libbtbb-2017-03-R2/wireshark/plugins/btbb/packet-btbb.c: In function ‘proto_reg_handoff_btbb’:
/home/jeffrey/Desktop/Ubertooth/libbtbb-2017-03-R2/wireshark/plugins/btbb/packet-btbb.c:572:16: warning: implicit declaration of function ‘new_create_dissector_handle’; did you mean ‘create_dissector_handle’? [-Wimplicit-function-declaration]
  btbb_handle = new_create_dissector_handle(dissect_btbb, proto_btbb);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                create_dissector_handle
/home/jeffrey/Desktop/Ubertooth/libbtbb-2017-03-R2/wireshark/plugins/btbb/packet-btbb.c:572:14: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  btbb_handle = new_create_dissector_handle(dissect_btbb, proto_btbb);
              ^
[ 80%] Building C object CMakeFiles/btbb.dir/packet-btbrlmp.c.o
/home/jeffrey/Desktop/Ubertooth/libbtbb-2017-03-R2/wireshark/plugins/btbb/packet-btbrlmp.c: In function ‘proto_register_btbrlmp’:
/home/jeffrey/Desktop/Ubertooth/libbtbb-2017-03-R2/wireshark/plugins/btbb/packet-btbrlmp.c:2864:32: warning: passing argument 2 of ‘register_dissector’ from incompatible pointer type [-Wincompatible-pointer-types]
  register_dissector("btbrlmp", dissect_btbrlmp, proto_btbrlmp);
                                ^~~~~~~~~~~~~~~
In file included from /home/jeffrey/Desktop/Ubertooth/libbtbb-2017-03-R2/wireshark/plugins/btbb/packet-btbrlmp.c:31:0:
/usr/include/wireshark/epan/packet.h:504:34: note: expected ‘dissector_t {aka int (*)(struct tvbuff *, struct _packet_info *, struct _proto_node *, void *)}’ but argument is of type ‘void (*)(tvbuff_t *, packet_info *, proto_tree *) {aka void (*)(struct tvbuff *, struct _packet_info *, struct _proto_node *)}’
 WS_DLL_PUBLIC dissector_handle_t register_dissector(const char *name, dissector_t dissector, const int proto);

**Comment by mikeryan** [comment]
Please try latest master branch and reopen if you have issues.
