### ISSUE TITLE
ubertooth-btle-libUSB-Error-Timeout-(-7)

### ISSUE THREAD

**Issue by ChenYenTing** [greatscottgadgets/ubertooth#324]
Hello

When I input " sudo ubertooth-btle -f " in virtual machine , it can run for a while and show this error.
How can I solve it ?
![image](https://user-images.githubusercontent.com/12229254/42742992-7e6ac956-88f2-11e8-9e43-570d02c5aece.png)

**Comment by pckbls** [comment]
See: Issue https://github.com/greatscottgadgets/ubertooth/issues/174

Best regards,
Patrick

**Comment by pckbls** [comment]
I cannot find the exact issue number but the developer once stated that there are a number of problems when trying to use the Ubertooth One inside a virtualized environment. He suggested to use a native Linux machine instead.

**Comment by mikeryan** [comment]
Indeed, Ubertooth runs poorly inside a VM and this type of timeout is one of the known issues. If you have a native OS X or Linux system, use that.
