### ISSUE TITLE
Ubertooth-btle no longer follows null targets

### ISSUE THREAD

**Issue by anotherfiz** [greatscottgadgets/ubertooth#327]
### Steps to reproduce
1. ubertooth-btle -t00:00:00:00:00:00
2. ubertooth-btle -A37 -f

### Expected behaviour
Ubertooth should continuously sniff advertising data on channel 37 and not attempt to follow any connection requests

### Actual behaviour
Ubertooth does not sniff any packets

### Version information
**Operating system**: Ubuntu 18.0.4 LTS

**Ubertooth tools version (ubertooth-rx -V):**
libubertooth 1.0 (2018-06-R1)

**libbtbb version:**
libbtbb 1.0 (2018-06-R1)

**Ubertooth firmware version (ubertooth-util -v):**

### Output
```ubertooth-btle -t00:00:00:00:00:00
target set to: 00:00:00:00:00:00
ubertooth-btle -A37 -f
<nothing>

**Comment by mikeryan** [comment]
This is a known issue. I plan to add a new command line option for advertising-only, perhaps -n for no-follow. Thoughts?

**Comment by anotherfiz** [comment]
Sounds great to me!
