### ISSUE TITLE
No ATT packets with ubertooth-btle 

### ISSUE THREAD

**Issue by catarinadf** [greatscottgadgets/ubertooth#332]
Hello everyone,

I 'm trying to sniff the bluetooth connection between my phone and a smart light bulb by typing in the terminal : $ubertooth-btle -f -t @MAC -c smartbulb.pcap. The problem is that there's no ATT packet . I only get ADV_IND and SCAN_REQ packets while I'm changing the bulb's color with my phone.

### Version information
Ubuntu 18.04

**Ubertooth tools version (ubertooth-rx -V):**
libubertooth 1.0 (2017-03-R2), libbtbb 1.0 (2017-03-R2)

**Ubertooth firmware version (ubertooth-util -v):**
Firmware version: 2017-03-R2 (API:1.02)

**Comment by tjhasan** [comment]
Hey, I know this is from 2 years ago, but I'm seeing the same issue. I was wondering how you fixed this?
