### ISSUE TITLE
ubertooth not working

### ISSUE THREAD

**Issue by studysession** [greatscottgadgets/ubertooth#333]
Would appreciate any help I can get. 

I ran ubertooth-btle and it said I needed a newer firmware version.
I downloaded the latested and flashed the ubertooth and now it just has 1 green light on. It had more lights on before the flash. Now no program can see it. 
I now get "could not open Ubertooth device"

I have never used it - right out of the package and now lost on what to do.

### Steps to reproduce
I do not have steps to reproduce

### Expected behavior
If I type the "ubertooth-util -v" I should get information about my device

### Actual behavior
Instead I get "could not open Ubertooth device"

### Version information
Most recent version of Ubuntu on a Dell laptop
Also tried it on Ubuntu Mate on a Raspberry Pi
Same result on both systems

**Comment by studysession** [comment]
Sorry guess I put platform in wrong area as version info - new to the sight so thought version info was my OS

Ubuntu (most recent everything) on my Dell laptop
Ubuntu Mate on my Raspberry Pi 3B (not the plus)

Same error on both
"could not open Ubertooth device"

Yes replugging in and out the device it just stays with the one light green and get the "could not open Ubertooth device" for any command I type.

Thank you

**Comment by studysession** [comment]
I copied the command off the github website
ubertooth-dfu -d bluetooth_rxtx.dfu -r

I downloaded and compiled it successfully and then did the command

BEFORE plugged in:
pi@pi-desktop:~$ lsusb
Bus 001 Device 007: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 001 Device 005: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

AFTER PLUGGED in and no change:
Bus 001 Device 007: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 001 Device 005: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Thanks

**Comment by studysession** [comment]
Found this - it is my exact problem. 

![uber1500x500](https://user-images.githubusercontent.com/43299354/46984794-0c5ed680-d0b5-11e8-928e-58238d224efe.jpg)

**Comment by studysession** [comment]
That worked - also 
the download I had already would not load so redownloaded, recompiled and it worked.

THANK YOU SO MUCH

**Comment by HangeZyh** [comment]
hello,
I get the same problem, i can't catch the device when exec command "lsusb" 
can u tell me the way you solve the bug?
THANKS
