### ISSUE TITLE
How can i use the packet injection feature?

### ISSUE THREAD

**Issue by davidHisense** [greatscottgadgets/ubertooth#334]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
I use the Ubertooth-tx, and find that non-function in it,so how could i use the packet injection feature?
Or it can not support packet injection feature cunrrently?

### Actual behaviour
Tell us what happens instead

### Version information
**Operating system**: 
Ubuntu 16.04

**Ubertooth tools version (ubertooth-rx -V):**
libubertooth 1.1 (2018-08-R1), libbtbb 1.0 (2018-06-R1)

**libbtbb version:**
libubertooth 1.1 (2018-08-R1), libbtbb 1.0 (2018-06-R1)

**Ubertooth firmware version (ubertooth-util -v):**
Firmware version: 2018-08-R1 (API:1.05)

If you are reporting a problem that involves third party software 
(Wireshark/Kismet/etc), please report the version here.

### Output
```
Insert any commandline or build output here
```

**Comment by mikeryan** [comment]
At present the only TX capabilities in Ubertooth are injecting ADV_IND packets into advertising channels.

**Comment by mikeryan** [comment]
That's correct.
