### ISSUE TITLE
Missing CMakeLists.txt missing in the root of the project

### ISSUE THREAD

**Issue by EinarHelgi** [greatscottgadgets/ubertooth#338]
### Steps to reproduce
1.
I am following the instructions in https://github.com/greatscottgadgets/ubertooth/wiki/Build-Guide
2.
It contains the following:
mkdir build
cd build
cmake ..
3.
When this is done, I get:

einarhelgi@debian:~/Downloads/ubertooth-2018-08-R1/build$ cmake ..
CMake Error: The source directory "/home/einarhelgi/Downloads/ubertooth-2018-08-R1" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
einarhelgi@debian:~/Downloads/ubertooth-2018-08-R1/build$ 

### Expected behaviour
Tell us what you expect should happen

### Actual behaviour
Tell us what happens instead

### Version information
**Operating system**:

**Ubertooth tools version (ubertooth-rx -V):**

**libbtbb version:**

**Ubertooth firmware version (ubertooth-util -v):**

If you are reporting a problem that involves third party software 
(Wireshark/Kismet/etc), please report the version here.

### Output
```
Insert any commandline or build output here
```

**Comment by dominicgs** [comment]
The line before `mkdir build` is `cd ubertooth-2018-08-R1/host`  I think you've missed the host directory from the end of that.

There is not meant to be a CMakeLists.txt in the root of the project.
