### ISSUE TITLE
Download file name collision

### ISSUE THREAD

**Issue by tomsaul** [greatscottgadgets/ubertooth#343]
Please use different names file names for the tools and firmware download files - they are currently the same, which forces them to be downloaded to different locations to use.

**Comment by tomsaul** [comment]
So they are - my confusion is that there are distinct links (that both point to the same file) for tools and firmware.

**Comment by dominicgs** [comment]
Ah yes, there are the source code links that GitHub produces, unfortunately we can't stop those from appearing :(
