### ISSUE TITLE
Capture other signals

### ISSUE THREAD

**Issue by XxSwiftflamexX** [greatscottgadgets/ubertooth#344]
How can you use the ubertooth to capture signsls other than Bluetooth? Such as: 802.11 FHSS (1MBit) and Some proprietary 2.4GHz wireless devices from the FAQ

**Comment by mikeryan** [comment]
You will have to write custom firmware to speak to other wireless devices. See this code for example of talking to a proprietary 2.4 GHz electric skateboard:

https://github.com/greatscottgadgets/ubertooth/blob/master/firmware/bluetooth_rxtx/ego.c

**Comment by mikeryan** [comment]
Closing this because I think the above covers it. Feel free to reopen if you have further questions.
