### ISSUE TITLE
Research institute or concerned to set up Ubertooth and sniff bluetooth

### ISSUE THREAD

**Issue by deepakedayillam** [greatscottgadgets/ubertooth#348]
Are there any Research consultancies, research institutes or companies who could help us with the setup to sniff Bluetooth packets using ‘Ubertooth one’ or other similar device and perform the following tasks
a)	Capture BT broadcasts
b)	Capture Pairing Handshakes
c)	Capture decrypted Point-to-Point communication
d)	Determine used Security Mode
e)	Determine used Security Levels

Regards
Deepak

**Comment by mikeryan** [comment]
If you are still interested in doing this, please reopen this issue.
