### ISSUE TITLE
How to send more than 21 bytes with cmd_le_set_adv_data?

### ISSUE THREAD

**Issue by evanslify** [greatscottgadgets/ubertooth#350]
### Steps to reproduce
1. Try sending more than 21 bytes with cmd_le_set_adv_data

### Expected behaviour
I'm trying to send an LE ADV_IND with length of over 21 bytes. Tried overwriting `LE_ADV_MAX_LEN` but seems like ubertooth's firmware(?) won't take it either.

### Actual behaviour
It says "LE advertising data too long".

### Version information
**Operating system**: Fedora 29

**Ubertooth tools version (ubertooth-rx -V):** libubertooth 1.1 (git-0adf33e*)

**libbtbb version:** libbtbb 1.0 (2017-03-R2)

**Ubertooth firmware version (ubertooth-util -v):** 2018-12-R1

**Comment by mossmann** [comment]
I'm confused as to why LE_ADV_MAX_LEN is set to 21 and why the firmware limits packet length similarly, so I'm hoping @mikeryan can shed some light on it.
