### ISSUE TITLE
Package python-pyside is not available

### ISSUE THREAD

**Issue by Crypto-Cowboy** [greatscottgadgets/ubertooth#355]
### Steps to reproduce
1. followed first step that is the same for all tutorials I have found
# udo apt-get install cmake libusb-1.0-0-dev make gcc g++ libbluetooth-dev pkg-config libpcap-dev python-numpy python-pyside python-qt4
2.
3.

### Expected behaviour

should verify versions and install

### Actual behaviour

After typing the first line command of the tutorial I get the following error
# sudo apt-get install cmake libusb-1.0-0-dev make gcc g++ libbluetooth-dev pkg-config libpcap-dev python-numpy python-pyside python-qt4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python-pyside is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-pyside' has no installation candidate

### Version information
**Operating system**:
Kali 2018.4 amd64 was my iso

**Ubertooth tools version (ubertooth-rx -V):**
2018-12

**libbtbb version:**
2018-12

**Ubertooth firmware version (ubertooth-util -v):**
command not found

If you are reporting a problem that involves third party software 
(Wireshark/Kismet/etc), please report the version here.

### Output
```
Insert any commandline or build output here
```

**Comment by bsb862** [comment]
I was having the same error with Kali. I used Ubuntu and for whatever reason it started working.

**Comment by Crypto-Cowboy** [comment]
I just tried it on Ubuntu and I got the same exact error. I also cant use specan-ui
root@kali:~# ubertooth-specan-ui 
bash: ubertooth-specan-ui: command not found

**Comment by GravesJake** [comment]
Have you tried installing pyside with pip?

**Comment by Crypto-Cowboy** [comment]
I have another issue open that is relater and will keep the thread going their
