### ISSUE TITLE
ubertooth-rx can not follow the bt device to capture data packages

### ISSUE THREAD

**Issue by davidHisense** [greatscottgadgets/ubertooth#357]
The operation as follows:
   ubertooth-rx -l D5521A -r bt.pcapng

But i can only get few packages,whether it can get the pairing and connecting packages like the tool 'ubertooth-btle'?

thanks

**Comment by GravesJake** [comment]
I'm not entirely sure what problem you're having. You're expecting to see more packets than you're currently seeing?

**Comment by mossmann** [comment]
It is normal for ubertooth-rx to receive only a small percentage of the packets of a classic Bluetooth connection.  Ubertooth does not have the capablity of following the hopping pattern for most classic Bluetooth devices like it does for Bluetooth Low Energy.
