### ISSUE TITLE
Is this software can support to sniff BLE 5.0 packet?

### ISSUE THREAD

**Issue by LifangLib** [greatscottgadgets/ubertooth#360]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what you expect should happen

### Actual behaviour
Tell us what happens instead

### Version information
**Operating system**:

**Ubertooth tools version (ubertooth-rx -V):**

**libbtbb version:**

**Ubertooth firmware version (ubertooth-util -v):**

If you are reporting a problem that involves third party software 
(Wireshark/Kismet/etc), please report the version here.

### Output
```
Insert any commandline or build output here
```

**Comment by mossmann** [comment]
Ubertooth One can detect Low Energy packets transmitted with the 1 Msym/s modulation.  According to the Core Specification 5.0, this includes all primary advertising packets.
