### ISSUE TITLE
Unable to make bluetooth_rxtx

### ISSUE THREAD

**Issue by ghost** [greatscottgadgets/ubertooth#37]
Thanks for your help in the past! I bought a Ubuntu laptop after seeing that running ubertooth on my Mac would not work. I've gotten much further, but I'm running into a problem:

When trying to run make in the bluetooth_rxtx directory, I get the following:

fatal: Not a git repository (or any of the parent directories): .git

------- begin -------
make: arm-none-eabi-gcc: Command not found
make: **\* [gccversion] Error 127

I had downloaded the ubertooth-2014-02-R2 using wget as directed in the Build Guide. Do I actually need to clone the project?

Or maybe my directory structure is causing a problem. I just created an 'uber' subdirectory in my home directory. I have successfully unpacked and installed the following projects, each in their own directory under my 'uber' directory:

kismet-2013-03-R1b
libbtbb2014-02-R2
pyusb-1.0.0b1
ubertooth2014-02-R2

Thanks in advance for any ideas that might help me get to the next step - looking forward to seeing some packets being sniffed sometime soon!

Jeff

**Comment by cgopalai** [comment]
I'm unable to make bluetooth_rxtx. It's failing during linking process and below is the last few lines of compilation output
Linking: bluetooth_rxtx.elf
arm-none-eabi-gcc -T LPC17xx_Linker_Script_with_bootloader.ld -mcpu=cortex-m3 -mthumb -mthumb-interwork -Wl,-Map=bluetooth_rxtx.map -Wl,--gc-sections -L../common -static -Wl,--start-group  -lc -lg -lstdc++ -lsupc++  -lgcc -lm  -Wl,--end-group  -o bluetooth_rxtx.elf bluetooth_rxtx.o bluetooth.o bluetooth_le.o ubertooth_usb.o cc2400_rangetest.o ../common/usb_serial.o ../common/serial_fifo.o ../common/LPC17xx_Startup.o ../common/LPC17xx_Interrupts.o ../common/ubertooth.o ../common/lpcusb/target/usbcontrol.o ../common/lpcusb/target/usbinit.o ../common/lpcusb/target/usbhw_lpc.o ../common/lpcusb/target/usbstdreq.o
/usr/lib/gcc/arm-none-eabi/4.8.2/../../../arm-none-eabi/bin/ld: cannot find -lstdc++
/usr/lib/gcc/arm-none-eabi/4.8.2/../../../arm-none-eabi/bin/ld: cannot find -lsupc++
collect2: error: ld returned 1 exit status
make: *** [bluetooth_rxtx.elf] Error 1

Any help would be greatly appreciated.

Here are my version of ubuntu details
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
