### ISSUE TITLE
Will Ubertooth work with active Bluetooth RFID tags?

### ISSUE THREAD

**Issue by Russ76** [greatscottgadgets/ubertooth#370]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what you expect should happen

### Actual behaviour
Tell us what happens instead

### Version information
**Operating system**:

**Ubertooth tools version (ubertooth-rx -V):**

**libbtbb version:**

**Ubertooth firmware version (ubertooth-util -v):**

If you are reporting a problem that involves third party software 
(Wireshark/Kismet/etc), please report the version here.

### Output
```
Insert any commandline or build output here
```

**Comment by GravesJake** [comment]
I don't have experience with RFID tags, but a good place to ask would be in the ubertooth IRC channel.

**Comment by mikeryan** [comment]
Those are BLE, so yes!
