### ISSUE TITLE
Ubertooth follow doesn't set the clock correctly

### ISSUE THREAD

**Issue by cathyz64** [greatscottgadgets/ubertooth#373]
In ubertooth-follow, it uses hci_read_clock_offset to get the hopping pattern of the slave device. However, the offset is right shifted by 2 so it shouldn't be clock += offset, it should be clock += offset<<2. But there is another problem, because usleep(10000) is called before that clock value is sent to the ubertooth. It would be better to create a connection to the ubertooth prior to reading the clock offset and then send clock + offset<<2 + delay immediately to the ubertooth. You can then delay and close out the connection. I have tested this method and it works perfectly for getting the correct slave clock and thus the correct hopping pattern.

**Comment by GravesJake** [comment]
Feel free to open a pull request with this change!

**Comment by mikeryan** [comment]
I second the request for a pull request @cathyz64

**Comment by aerial64** [comment]
I did the pull request last summer. I think it made it through but I'm off on other things and haven't followed up.

**Comment by cathyz64** [comment]
I believe I made the pull request last summer. I think it went through with a few build errors that may need to be resolved on the gsg side of things.

**Comment by mikeryan** [comment]
Thanks, I missed that one. I will review the PR before our next release.
