### ISSUE TITLE
Another libUSB Error: Operation timed out:  (-7)

### ISSUE THREAD

**Issue by 00Roeder** [greatscottgadgets/ubertooth#379]
### Steps to reproduce
1. ubertooth-btle -n -c /tmp/pipe

### Expected behaviour
dumping into the pipe

### Actual behaviour
libUSB Error: Operation timed out:  (-7)
after 10-60 sec (varies)

### Version information
**Operating system**:
Kali 2019
**Ubertooth tools version (ubertooth-rx -V):**
libubertooth 1.1 (2018-12-R1), libbtbb 1.0 (2018-06-R1)

**Ubertooth firmware version (ubertooth-util -v):**
Firmware version: 2018-12-R1 (API:1.06)

**Comment by freqyXin** [comment]
I'm having identical issues. Any luck finding a work around or solution?

**Comment by neomorphus** [comment]
i am facing the same issue, does anyone find a solution?

**Comment by tranzmatt** [comment]
I'm having an issue with mine, but with kismet inside a docker.  I can run `ubertooth-rx ok`, but `kismet -c ubertooth` borks with a `libUSB error (-4)`.  I was wondering if these were related.

**Comment by cdrdzsilva** [comment]
Anyone was able to find the solution for this?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
