### ISSUE TITLE
Output files from "ubertooth-specan -g -d output.dat" are garbled codes

### ISSUE THREAD

**Issue by BOZHENG001** [greatscottgadgets/ubertooth#380]
### Steps to reproduce
1. Install libbtbb-2017-03-R2 and every other software needed in raspberry pi 3 model B+ (I tried to use libbtbb-2018-12-R1, but some commands did not work well, like `ubertooth-specan-ui`, it would ask for some libs from python, like PySide2 or specan, depends on the version of python I used to run the file, python2 or python3).
2. With libbtbb-2017-03-R2, `ubertooth-specan-ui` runs very well. After that, i would like to extract data about spectrum out, so i ran `unbertooth-specan -g -d output.dat`. I did have an output file in my raspberry pi, but it is always garbled/error/unintelligent codes inside.

### Expected behaviour
I would like to see some readable codes inside "output.dat", like running the command `ubertooth-specan -G` in terminal, timestamp, frequency, RSSI and etc..

### Actual behaviour
In "output.dat", i saw garbled/error/unintelligent codes, like "vÔ	wÔ	xÓ	yÔ	zÔ	{Ö	|×	}×	~Õ	Ô	Ö	Ö	Ò	Ó	Õ	Ô	×"

### Version information
Raspbian GNU/Linux 10 (buster)

**Ubertooth tools version (ubertooth-rx -V):**
ubertooth-2018-12-R1

**libbtbb version:**
libbtbb-2017-03-R2

**Ubertooth firmware version (ubertooth-util -v):**
2018-12-R1 (API:1.06)

If you are reporting a problem that involves third party software 
(Wireshark/Kismet/etc), please report the version here.

### Output
vÔ	wÔ	xÓ	yÔ	zÔ	{Ö	|×	}×	~Õ	Ô	Ö	Ö	Ò	Ó	Õ	Ô	×

Insert any commandline or build output here

**Comment by mikeryan** [comment]
`-d` is a deprecated option that will be going away in the next release
