### ISSUE TITLE
How can I use ubertooth-one for getting the MAC and name of the nearby bluetooth device?

### ISSUE THREAD

**Issue by KeeWong1987** [greatscottgadgets/ubertooth#386]
Dear sir,

### Problems
Currently, I use ubertooth-one to grab broadcast packets and data packets and find that the MAC address in the packet is random.  I want to find the method to get the real (public) MAC address of the nearby BT device.  Could you teach me how can I do with it?

### Version information
Linux - Ubuntu 16.04.6 LTS

libubertooth 1.1 (2018-12-R1), libbtbb 1.0 (2018-06-R1)
Firmware version: 2018-12-R1 (API:1.06)

Many thanks and looking forward to hearing from you.

**Comment by evanslify** [comment]
You cannot get public MAC address unless device is trying to connect to another device. In that case, you can filter all but CONNECT_REQ packets, and one of the device would reveal its public MAC.
