### ISSUE TITLE
How to set advertizing data for ubertooth-btle?

### ISSUE THREAD

**Issue by StevenRudenko** [greatscottgadgets/ubertooth#387]
### Steps to reproduce
1. `ubertooth-btle -s00:11:22:33:44:55`

### Expected behaviour
Ubertooth device is scanabled within address `00:11:22:33:44:55`. Advertising data is readable

### Actual behaviour
Ubertooth device is no visible while scanning

### Version information
**Operating system**: MacOS 10.14.6 (18G95)

**Ubertooth tools version (ubertooth-rx -V):** libubertooth 1.1 (2018-12-R1), libbtbb 1.0 (2018-06-R1)

**libbtbb version:** 2018-12-R1?

**Ubertooth firmware version (ubertooth-util -v):** Firmware version: 2018-12-R1 (API:1.06)

If you are reporting a problem that involves third party software 
(Wireshark/Kismet/etc), please report the version here.

### Output
```
 ubertooth-btle -s00:11:22:33:44:55
```

**Comment by nishant412** [comment]
I am facing the same issue. I have the same ubertooth firmware and tools versions as above, just using it on a different OS (Ubuntu 18.04). When I issue the fake advertising packets command with -s flag, I see the TXLED rapidly and continuously blinking but it doesn't actually transmit advertisements. 

To check for advertisements, I used the nrfconnect app on my Android phone, and also just in case checked with a USRP for any transmissions on the three advertising channels. Couldn't see any advertisements.

Thanks 
Nishant

**Comment by evanslify** [comment]
Check `ubertooth-btle.c`. The data you wanted to change is in `uint8_t adv_data[]`. 
Note that you cannot exceed 21 bytes - https://github.com/greatscottgadgets/ubertooth/issues/350

**Comment by StevenRudenko** [comment]
@evanslify thank, but problem is that device is not advertising itself at all. do you know how to fix that?

**Comment by evanslify** [comment]
Are you listening on the right channel?

**Comment by zhaohuansi** [comment]
Chinese？
