### ISSUE TITLE
Ubertooth library compile steps to use with Android OS

### ISSUE THREAD

**Issue by StevenRudenko** [greatscottgadgets/ubertooth#388]
Could anyone suggest the way to build ubertooth library to be used on Android OS?

### Steps to reproduce
1. Clone Ubertooth and libbtbb library.
2. Compile within ndk-build

### Expected behaviour
.so libraries are compiled to be used with NDK on Android OS

### Actual behaviour
Can't find a way to compile the libraries?

### Version information
**Operating system**:

**Ubertooth tools version (ubertooth-rx -V):** libubertooth 1.1 (2018-12-R1), libbtbb 1.0 (2018-06-R1)

**libbtbb version:** 2018-12-R1

**Ubertooth firmware version (ubertooth-util -v):** Firmware version: 2018-12-R1 (API:1.06)

If you are reporting a problem that involves third party software 
**Android Studio**: 3.5.2
**ndk-build --version** : GNU Make 3.81

**Comment by mikeryan** [comment]
Android is not a supported platform.
