### ISSUE TITLE
ubertooth-btle -U

### ISSUE THREAD

**Issue by KeeWong1987** [greatscottgadgets/ubertooth#392]
Dear sir,

[Problems]
Suppose that i have two ubertooth devices. The command parameter -U<0-7> shows that we should to set the index<0-7> of ubertooth device when using 'ubertooth-btle -U' command.  
But how do i know the index of the corresponding devices when using the command and how can I use two ubertooth devices to work simultaneously?

[Version information]
Linux - Ubuntu 16.04.6 LTS

libubertooth 1.1 (2018-12-R1), libbtbb 1.0 (2018-06-R1)
Firmware version: 2018-12-R1 (API:1.06)

Many thanks and looking forward to hearing from you.

**Comment by GravesJake** [comment]
The command `ubertooth-util -I` will help you identify each device by flashing the LEDs. 

Use `ubertooth-util -h` for more info.
