### ISSUE TITLE
Migrating libBTBB with gr-bluetooth

### ISSUE THREAD

**Issue by tylerone1** [greatscottgadgets/ubertooth#399]
Hi all!
I bought HackRF SDR and also ubertooth.
I'm trying to write a simple BR/EDR sniffer using gr-bluetooth.
Is there any guide how to write sniffer using gr-bluetooth and libBTBB?

I saw some documentation about gr-bluetooth in the Wiki:
https://github.com/greatscottgadgets/ubertooth/wiki/Bluetooth-Captures-in-PCAP#BREDR

> Since PCAP has general applicability to packet capture, it made sense to provide a vendor-neutral, generic view of Bluetooth capture. The allocated DLTs can be applied to current and future versions of both ubertooth and gr-bluetooth, and potentially other RF capture tools as well.

I don't want to hop channels, just to get LAPs through the hackrf, it would just make my life much easier if I can use the ubertooth code to do it. you did a great job

So i assume that there might be an answer to my question.
Thank so much!
Tyler.

**Comment by nic-kaczinsky** [comment]
@tylerone1  how are you doing?
I'm currently working on the similar thing and I'm interested in your progress. Can we talk about it?

**Comment by mikeryan** [comment]
https://github.com/greatscottgadgets/gr-bluetooth is the project you seek
