### ISSUE TITLE
No package 'bluez' found after executing 'cmake ..'  on Macos(version 10.15.3)

### ISSUE THREAD

**Issue by warren-qian** [greatscottgadgets/ubertooth#402]
### Steps to reproduce
1.Download ubertooth-2018-12-R1.tar.xz and uncompress
2.go into  /ubertooth-2018-12-R1/host/ and create a build folder
3.switch to  /ubertooth-2018-12-R1/host/build 
4.execute 'make ..'

### Expected behaviour
install ubertooth successful without any error info.(error info in ###Output)

### Actual behaviour
install ubertooth failed cause of No package 'bulez'.

### Version information
**Operating system**:
Macos(version 10.15.3)

### Output
**warrenq@Warrens-MacBook-Pro build % pwd
/Users/warrenq/ubertooth-2018-12-R1/host/build
warrenq@Warrens-MacBook-Pro build % cmake ..
CMake Warning (dev) at CMakeLists.txt:28 (set):
  implicitly converting 'INT' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:29 (set):
  implicitly converting 'INT' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Setting version string 2018-12-R1
-- Building shared library
-- Checking for module 'bluez'
--   No package 'bluez' found
-- Could NOT find LIBBLUETOOTH (missing:  LIBBLUETOOTH_LIBRARIES LIBBLUETOOTH_INCLUDE_DIR) 
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   ubertooth

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/warrenq/ubertooth-2018-12-R1/host/build
warrenq@Warrens-MacBook-Pro build %**

**Comment by mikeryan** [comment]
This is expected behavior. BlueZ is not available on macOS and some of the features of `ubertooth-scan` will not be available. The rest of the tools will work.
