### ISSUE TITLE
ubertooth is not recognized.

### ISSUE THREAD

**Issue by greym00n** [greatscottgadgets/ubertooth#418]
### Steps to reproduce
1. insert the Ubertooth one into USB slot
2.
3.

### Expected behaviour
It should be recognized when I put the command "lsusb".

### Actual behaviour
1. not recognized.
2. My led state
RSTLED = ON(green)
USBLED = **OFF**
1V8LED = **OFF**
TXLED = ON
RXLED = ON
USRLED = ON

I don't know what this state means.

I've tried to force the device to enter the DFU mode by connecting the two holes (1 and 2).
( I tried '1 and 2', and '1 and 3'.)
However, it didn't work at all. The above state was not changed.

### Version information
**Operating system**:
Linux 16.04

**Ubertooth tools version (ubertooth-rx -V):**
libubertooth 1.1 (git-7f86811*), libbtbb 1.0 (git-7f86811*)

**libbtbb version:**
2018-12-R1

**Ubertooth firmware version (ubertooth-util -v):**
was not able to check,
it said "could not open Ubertooth device"

If you are reporting a problem that involves third party software 
(Wireshark/Kismet/etc), please report the version here.
no.
### Output
nothing

**Comment by mikeryan** [comment]
When forcing DFU mode, did you have the pins jumpered while inserting the board?

**Comment by greym00n** [comment]
thank you

**Comment by csims2004-cloud** [comment]
I am facing the same issue with a clone ubertooth (I know it's likely because its a clone) but when I use the port method it doesn't go into the dfu mode
