### ISSUE TITLE
Can I use ubertooth under WSL

### ISSUE THREAD

**Issue by Donghua-Gu-CardinalPeak** [greatscottgadgets/ubertooth#428]
I have ubuntu under windows 10 WSL, can ubertooth work in this environment? 

### Steps to reproduce
1. followed the instruction to install all the necessary libraries under ubuntu in windows wsl
2. when I run kismet, I got error: Ubertooth 'ubertooth' failed to open device' Resource temporaily unavailable
3. under terminal, I run sudo lsusb, and there is nothing showing up, but I do see ubertooth One under windows Device Manager

### Expected behaviour
capture package

### Actual behaviour
ubertooth fails to open device and lsusb returns nothing

### Version information
**Operating system**: windows 10, wsl2, ubuntu 18.04.2.LTS

**Ubertooth tools version (ubertooth-rx -V):**
libubertooth 1.1 (2018-12-R1), 

**libbtbb version:**
libbtbb 1.0 (2018-06-R1)

**Ubertooth firmware version (ubertooth-util -v):**
I can't check this because error "could not open Ubertooth device"

If you are reporting a problem that involves third party software 
(Wireshark/Kismet/etc), please report the version here.

### Output
```
Insert any commandline or build output here
```

**Comment by mikeryan** [comment]
Looks like this isn't a supported platform.
