### ISSUE TITLE
[NOT REALLY AN ISSUE]

### ISSUE THREAD

**Issue by DeityOfChaos** [greatscottgadgets/ubertooth#430]
After partially reading this article ( https://doi.org/10.1145/2906388.2906403 ), a guy managed to add firmware code to UberTooth, making it even more capable and efficient. The article is worth reading but the project seems to be abandoned with no support.

The guy's project can be found at: https://github.com/albazrqa/BluEar 

And could be a possible solution to adaptive hopping issues, allegedly with >90% packet capture rate in dynamic environments

**Comment by mikeryan** [comment]
Thanks for the pointer to BluEar. I think a link like that might belong on the wiki. Closing this as it's not an issue.
