### ISSUE TITLE
android support 

### ISSUE THREAD

**Issue by ghost** [greatscottgadgets/ubertooth#44]
i made a request here https://github.com/mikeryan/crackle/issues/4#issuecomment-67890981 and it would be possible to make an app for android to use ubertooth, i was thinking of having ubertooth connected to my nexus(nethunter) so would that be possible?

**Comment by sosobiao** [comment]
do you means https://github.com/gnychis/ubertooth-android

**Comment by Zaxscdvf** [comment]
@sosobiao  thanks i will take a look.
