### ISSUE TITLE
ubertooth-scan fails to find device

### ISSUE THREAD

**Issue by acidjazz** [greatscottgadgets/ubertooth#45]
most all other ubertooth tools work fine, ubertooth-rx shows packets/etc, but ubertooth-scan just keeps reporting back:

```
root@raspberrypi:~# ubertooth-scan
opening socket: No such device
```

more info:

```

root@raspberrypi:~# ubertooth-util -v
Firmware revision: git-4412704
root@raspberrypi:~# ubertooth-util -V
ubertooth git-4412704 (dominicgs@mercury) Wed Jan 29 20:38:22 GMT 2014
root@raspberrypi:~#

```

**Comment by Daniel-Katz** [comment]
I had the exact same problem you originally had, in that whenever I try to run the command:

Inspiron-1520:~$ ubertooth-scan
opening socket: No such device

How did you fix this problem?
