### ISSUE TITLE
Ubertooth one

### ISSUE THREAD

**Issue by grisuthesmaug** [greatscottgadgets/ubertooth#457]
### Steps to reproduce
1. Plug Module into USB Drive
2. Nothing happens
3. And i wonder....

### Expected behaviour

First I tried to use it in MacOS but the USB device wasn't recognized.
Then I tried it in VMware with Ubuntu 20.x and was able to see the usb device..

First time i tried to use it the usb connection was recognozied. I tried to upate the firmware  with:

ubertooth-dfu -d bluetooth_rxtx.dfu -r

and got the message " control message unsupported" multiple times. After unplugging and replgugging the device it was never seen again with "dmesg".

I tried to reboot it into DFU Mode by connecting P4-0 with P4-3 but also on this way there is no device detected in dmesg.

I tried to connect it to a bare metal Ubuntu 18.x machine with the same result

### Actual behaviour

All 4 blue LED a light up, but not device is detected by usb.

The one directly at the usb port:  permanent on blue
1V6: permanent on blue
TX: permanent on blue
RX: while connecting to usb blinks 3x after this, permanent on blue

USB(R?): never ligths up 

### Version information
**Operating system**:
Ubuntu 18.x
Ubuntu 20.x in Vmware on MacOS Host
MacOS 11.4

**Ubertooth tools version (ubertooth-rx -V):**

libubertooth 1.1 (git-4499a14), 

**libbtbb version:**

libbtbb 1.0 (git-4499a14)

**Ubertooth firmware version (ubertooth-util -v):**

no connectivity 

If you are reporting a problem that involves third party software 
(Wireshark/Kismet/etc), please report the version here.

### Output
```
Insert any commandline or build output here
```

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
