### ISSUE TITLE
MacPorts documentation out of date

### ISSUE THREAD

**Issue by mossmann** [greatscottgadgets/ubertooth#463]
Once we have resolved #453 we should update the command in our documentation that we suggest for installing prerequisites with MacPorts:

```
sudo port install libusb wget cmake python27 py27-numpy py27-pyside
```

We should require python3 now, not python2, and we appear to be missing libpcap and pkgconfig.

This is in: https://ubertooth.readthedocs.io/en/latest/building_from_git.html
And it is also in various release notes. We should make sure that future release notes use the correct command.

**Comment by mossmann** [comment]
I have no idea what I was looking at when I created this issue, but it looks like the documentation has been correct since December 2020.

**Comment by barracuda156** [comment]
@mossmann Is the port even available on Macports?

**Comment by straithe** [comment]
Can you please open your question in a new issue? That way I'll be able to make sure the team gets to it.

**Comment by barracuda156** [comment]
> Can you please open your question in a new issue? That way I'll be able to make sure the team gets to it.

@straithe Thanks, I will. In fact, looks like the port is not there, and I will see if I can bring it into Macports.
`libbtbb` submitted: https://github.com/macports/macports-ports/pull/15851

**Comment by straithe** [comment]
Thank you. That is greatly appreciated.
