### ISSUE TITLE
No module name 'numpy' error

### ISSUE THREAD

**Issue by Purple23200** [greatscottgadgets/ubertooth#466]
ubuntu@ubuntu:~$ ubertooth-specan-ui
Traceback (most recent call last):
  File "/usr/bin/ubertooth-specan-ui", line 25, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'

I was able to use ubertooth the other day and had this problem and fixed it, but i'm having this problem again and i'm unsure how it keeps happening because numpy is up to date.

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
