### ISSUE TITLE
which hardware?

### ISSUE THREAD

**Issue by Huibuh2010** [greatscottgadgets/ubertooth#467]
hey guys,

can anybody tell me a good hardware for bluetooth sniffing? thanks

**Comment by straithe** [comment]
Ubertooth One has some capability as a sniffer, but its main feature is the ability to detect and identify active Bluetooth devices. If you are trying to sniff Bluetooth Low Energy that is narrowband so hardware options are available. Regular Bluetooth is more difficult to sniff as it uses frequency hopping that bounces over an ~80MHz range. You would need a device that knows how to follow the frequency hopping in real time. There are a wide range of dedicated sniffers, but the selection depends on your particular need. 

Can you give a better description of the problem you are tackling?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
