### ISSUE TITLE
Malformed Packet

### ISSUE THREAD

**Issue by Geranium1024** [greatscottgadgets/ubertooth#491]
1. Malformed Packet
![图片](https://user-images.githubusercontent.com/102017138/159862267-1e266450-5f1d-459f-8aa3-32245d8529cf.png)
2.Version information
Firmware version: 2020-12-R1 (API:1.07)
ubertooth 2020-12-R1 (mikeryan@steel) Fri Dec 25 13:55:05 PST 2020
3.Output
$ubertooth-btle -n   
![图片](https://user-images.githubusercontent.com/102017138/159861258-378204a7-9d99-44b9-b637-ccf1ce13c32f.png)

How to solve this problem? 
Thanks !

**Comment by ztroop** [comment]
I'm seeing this as well. Any suggestions on how to proceed?

**Comment by straithe** [comment]
@Geranium1024 did @ztroop's suggestion work for you?

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
