### ISSUE TITLE
Max Capture Size? Documentation Needed

### ISSUE THREAD

**Issue by ztroop** [greatscottgadgets/ubertooth#494]
There was a conversation in the Discord channel that suggested that the device has a limited capture length for BTLE packets. We should probably update the documentation to reflect this. What is it? 70 bytes? (What I'm currently observing, anyhow...)

**Comment by ztroop** [comment]
Relates to #468. It looks like 50 bytes is the limit? However, I'm seeing packets in my capture that hit 70 bytes consistently.

**Comment by straithe** [comment]
50 bytes is the limit for BTLE.
