### ISSUE TITLE
libubertooth not included in debian bookworm

### ISSUE THREAD

**Issue by dragorn** [greatscottgadgets/ubertooth#503]
Looks like debian bookworm isn't currently including libubertooth (or libubertooth-dev):

https://packages.debian.org/search?searchon=names&keywords=libubertooth

libbtbb is still present however:

https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=libbtbb

**Comment by straithe** [comment]
Thank you for the information. Is there something you would like us to change, or are you just passing along information?

**Comment by dragorn** [comment]
We discussed it on discord and you asked me to open the ticket. I’m passing along information per request.

**Comment by Mousketeer** [comment]
The window for bookworm is closing, I fear the entire ubertooth ecosystem might be left out.

**Comment by straithe** [comment]
Do you know the deadline or who to talk to to get Ubertooth added?

**Comment by paultag** [comment]
The window has been missed. At this point you'd need to talk to the release
managers.

https://release.debian.org/bullseye/freeze_policy.html#soft

**Comment by miek** [comment]
It turns out that it did actually make it into bookworm in time, the maintainers backported that fix <https://metadata.ftp-master.debian.org/changelogs//main/u/ubertooth/ubertooth_2018.12.R1-5.1_changelog> :tada:

**Comment by paultag** [comment]
Slight bit of pendantry, that was a non-maintainer upload, so `bunk@` was nice enough to fix it for Bookworm, not the Debian maintainer(s) - I should have checked before saying the window has been missed. Sorry for the noise. We can likely close this bug.

**Comment by straithe** [comment]
Thank you for the update. I can see here that it made it in: https://packages.debian.org/bookworm/libubertooth-dev
