### ISSUE TITLE
How do I get Ubertooth One to work on Yummy?

### ISSUE THREAD

**Issue by E9Mack** [greatscottgadgets/ubertooth#505]
Hello there... I'm trying to get Ubertooth One working on Yummy, this code stuff is new to me so... I am close tho. Anyway after starting Kismet the terminal finishes with: INFO: Could not open system plugin directory (usr/lib/kismet/), skipping: no such file or directory   then INFO: Did not find a user plugin directory (/home/cwjohnson/.kismet//plugins/, skipping: no such file or directory    I am able to run Kismet sniffing on the Bluetooth card in the laptop though which I thought was cool. I would like to see Ubertooth hooked up though! Thank you

**Comment by straithe** [comment]
I do not know what Yummy is. Do you have a link to it that I can review?

**Comment by E9Mack** [comment]
Hi, sorry I thought Ubuntu 22.04.1 was called Yummy.

**Comment by straithe** [comment]
Thank you for the clarification. When you plug in the Ubertooth and type in `lsusb` what output do you get?

**Comment by E9Mack** [comment]
So this is not the computer I'm using for that. But I see it shows fine it's a matter of API mismatch I guess?

**Comment by straithe** [comment]
Can you please clarify? I don't understand what is not the computer you are using for what.

**Comment by E9Mack** [comment]
I mean, this computer I'm chatting to you on, is not the linux machine I have ubertooth on. I will get organized another day and hopefully I'll find you then? I didn't think I was going to hear from anyone honestly by now. Thank you though!

**Comment by straithe** [comment]
Thanks for the clarification. Please update the issue when you can.

**Comment by straithe** [comment]
@E9Mack do you have any updates for me?

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
