### ISSUE TITLE
Kail fail to update the firmware

### ISSUE THREAD

**Issue by YY-chen555** [greatscottgadgets/ubertooth#506]
### Steps to reproduce
1.Now my ubertooth version is 2017,but i want it to be newlest.
![image](https://user-images.githubusercontent.com/82623124/197703706-b78ee012-3140-45fa-9bc4-c91c6109d8be.png)

2.when i use `ubertooth-dfu -d bluetooth_rxtx.dfu -r`
![image](https://user-images.githubusercontent.com/82623124/197703895-cb96f788-5d74-46ad-a61b-88fc5ab981d3.png)

When I execute this step in the vmware kail, I get an error. Every time I execute it, It switches to DFU mode, and then the USB display cannot be recognized. At the same time, the four red indicators from dark to light on the hardware are looping the marquee.

Hwo can i solve this.Thanks

**Comment by straithe** [comment]
I suggest trying to update your Ubertooth without using a VM. Most VMs have USB pass through errors that can make upgrading difficult.

**Comment by YY-chen555** [comment]
> 我建议尝试在不使用 VM 的情况下更新您的 Ubertooth。大多数 VM 都存在 USB 直通错误，这会使升级变得困难。
You are right.
I have done the upgrade via JTAG.
Thanks

**Comment by straithe** [comment]
May I close this issue as complete now, @YY-chen555 ?

**Comment by YY-chen555** [comment]
> yes and thank you!
