### ISSUE TITLE
ubertooth-btle channel map support

### ISSUE THREAD

**Issue by stephanbehrens** [greatscottgadgets/ubertooth#51]
If the host sends a  LL_CHANNEL_MAP_REQ the ubertooth can not follow the connection anymore. This happens because the ubertooth does not register the new channel map which is a part of the LL_CHANNEL_MAP_REQ data packet. If the slave confirms the new channel map request the ubertooth is out of sync and stops following. The LL_CHANNEL_MAP_REQ consists of:
- channel map (ChM) / 5 octets
- Instant / 2 octets

(see Bluetooth Specification v.4.0 / 2.4.2.2 LL_CHANNEL_MAP_REQ / p.2212)

For example it could be:   _ff:07:c0:ff:1f:58:00_
- ff:07:c0:ff:1f    Channel map (ChM)
- 58:00     Instant

Each bit of the channel map represents a channel (1=used, 0=unused):

Channel 38 ---------------------------------- Channel 0
11111111-00000111-11000000-11111111-00011111

Example leads to the following active / used channels:   1-4, 8-15, 22-26, 32-37.
(Adv. channels are already excluded)

**Next channel hop:**   If there has been a channel map update the next channel hop (in btle_next_hop) has to be calculated different. The Bluetooth specification says if the calculated channel is an unused channel we have to use a different algorithm:

remappingIndex = unmappedChannel **mod** numUsedChannels
- numUsedChannels = number of used channels in the channel map. 
- This would be 23 used channel for the example above.

(see Bluetooth Specification v.4.0 / 4.5.8.2 Channel Selection / p.2238)

I added some thoughts to the end of this post. Actually i did some changes at bluetooth_le.h, bluetooth_le.c and bluetooth_rxtx.c. It's just a starting point for discussions and some tests :) 

see: [branch channel_map_support](https://github.com/stephanbehrens/ubertooth/tree/channel_map_support)

---

Additional stuff:
- The Opcode for LL_CHANNEL_MAP_REQ is 0x01.

---

Some easy thoughts:

![btle_next_hop](https://cloud.githubusercontent.com/assets/4303594/6028581/f09f3482-abea-11e4-957b-e4fa97c3a471.png)
![connection_follow_cb](https://cloud.githubusercontent.com/assets/4303594/6028582/f0c9bd10-abea-11e4-88bb-dd1ea7f2541b.png)

**Comment by mikeryan** [comment]
This is implemented in the latest pre-release 2018-06-R1. Please give it a try.
