### ISSUE TITLE
ubertooth-btle: lell_pcap_ppi_create_file: Permission denied

### ISSUE THREAD

**Issue by abcde-r** [greatscottgadgets/ubertooth#517]
### Steps to reproduce
I have the same issue as #413 which was just closed because of inactivity.

I am following the Ubertooth w/ Wireshark instructions from here: https://ubertooth.readthedocs.io/en/latest/capturing_BLE_Wireshark.html but the issue seems to be with ubertooth, not wireshark.

### Expected behaviour

Ubertooth streaming packets to /tmp/pipe for wireshark to parse.

### Actual behaviour
Without sudo: 

```
ubertooth-btle -f -c /tmp/pipe
libUSB Error: Access denied (insufficient permissions):  (-3)
could not open Ubertooth device
```

With sudo:

```
sudo ubertooth-btle -f -c /tmp/pipe
ubertooth-btle: lell_pcap_ppi_create_file: : Permission denied
```

### Version information
**Operating system**:
I am on Ubuntu 20.04 LTS

**Ubertooth tools version (ubertooth-rx -V):**
libubertooth 1.1 (2018-12-R1)

**libbtbb version:**
 libbtbb 1.0 (2018-06-R1)

**Ubertooth firmware version (ubertooth-util -v):**
Firmware version: git-15e931f (API:1.05)

### Output
```
sudo ubertooth-btle -f -c /tmp/pipe
ubertooth-btle: lell_pcap_ppi_create_file: : Permission denied
```

Note: Per #255 I did ```sudo adduser user plugdev``` but the issue persists even after that.

**Comment by abcde-r** [comment]
I'm not quite sure how I fixed this, because I was fighting with other errors for wireshark not launching correctly, but some steps that were involved in debugging were:

chmod +x /usr/bin/dumpcap
sudo adduser user wireshark

**Comment by w3b5h3ll** [comment]
I run it by root permission. All is fine.
