### ISSUE TITLE
Where is the nine test points in the hardware?

### ISSUE THREAD

**Issue by sada45** [greatscottgadgets/ubertooth#523]
Hi!
I have brought a Ubertooth One for testing and I want to collect the I/Q sample from the ATEST1/2 pin of the CC2400 with an external ADC. I find there is a group of "test points" in the schematic, which includes nine points. But there is not indictaion on the hardware. 
If find nine contact points behind the CC2400 (red circle in the picture), are these test points? It seems that there is a 3.3v point, but I test all of the points and none of them has 3.3v voltage.
![屏幕截图 2024-01-10 163642](https://github.com/greatscottgadgets/ubertooth/assets/49777976/ae46b81f-1822-4de7-a7cf-adf4d1e922d6)

**Comment by martinling** [comment]
No, that group of 9 are vias to the ground pad on the back of the CC2400 chip. The test points are the exposed circles without holes in them. Here's a screenshot with the names visible:

![image](https://github.com/greatscottgadgets/ubertooth/assets/673823/953df16f-0820-4346-9ea8-0b50f88143b2)

ATEST1 and ATEST2 are the two test points just below the start of the "EXPAND" text.

**Comment by sada45** [comment]
Wow, thank you very much for the quick reply!
