### ISSUE TITLE
Can't use ubertooth-scan -U<#> with multiple Ubertooth Ones

### ISSUE THREAD

**Issue by Truitt23** [greatscottgadgets/ubertooth#53]
::Version 2014-04-R1::
::ubertooth git-4412704 (dominicgs@mercury) Wed Jan 29 20:38:22 GMT 2014::

I'm attempting to run ubertooth-scan with multiple Ubertooth Ones plugged in and the software is failing.
Obviously I get the standard, "multiple Ubertooth devices found! Use '-U' to specify device number" message if I don't indicate the -U option.  However, adding the -U option returns, "ubertooth-scan: invalid option -- 'U'".

Thanks. --Truitt

**Comment by dominicgs** [comment]
Fixed in git repository.  Will be in the next release.

**Comment by Truitt23** [comment]
Thanks, Dominic.  Keep up up the great work!
