### ISSUE TITLE
Server reports PHY type 'BTBB', but there is no support for it in the client.

### ISSUE THREAD

**Issue by cliveg8739** [greatscottgadgets/ubertooth#68]
Good morning,

I am trying to set up an Ubertooth One with Kismet. I have installed Kismet, and libbtbb from source and then installed the Ubertooth Plugin, following the instructions provided in the Git repo. I start the Kismet server with `kismet_server -c ubertooth` and it seems to pick up the Ubertooth. 

When I start the client I get the following error: `Server reports PHY type 'BTBB', but there is no support for it in the client.`

Thanks.

**Comment by dominicgs** [comment]
Could you tell me which versions of libbtbb, Ubertooth and Kissmet you are using?

**Comment by cliveg8739** [comment]
Kismet 2012-GIT-R0
libbtbb 0.3
Ubertooth git-4412704
